### ISSUE TITLE
2016年11月のpotatotips （トレタ様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#28]
## 主催者様

株式会社トレタ様（担当：堀見さん @horimislime  ）
## 開催日

2016年11月29日
18:30 開場 19:00 開始
## 場所

株式会社トレタ様オフィス

**Comment by horimislime** [comment]
@tokorom さん、ご無沙汰しております。

日程なのですが、

- 11/29(火)
- 18:30会場
- 19:00開始
- 22:00終了

で考えております。いかがでしょうか？

**Comment by tokorom** [comment]
@horimislime ご調整ありがとうございます！問題ありません。

これからconnpassのページのドラフトを作成させていただきます :bow:

**Comment by tokorom** [comment]
@horimislime connpassのイベントページのドラフトを作成させていただきました。

お手数ですが、以下ご確認お願いします。

http://connpass.com/event/43344/edit/

- [ ] Organizer（管理者）を必要に応じて追加をお願いします
- [ ] 開催日時や場所などに変更がございましたら更新をお願いします
- [ ] Event Imageの登録（特に決まりはありません。御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います。）
- [ ] 募集枠を会場や御社ご状況に合わせてご変更ください
- [ ] Description部分に変更の必要な箇所がありましたら編集をお願いします（TODOマークを付けております）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 更新が終わりましたら良きタイミングで公開いただいて大丈夫です 

その他、不明事項などありましたらお気軽にmentionください :)

**Comment by horimislime** [comment]
@tokorom 
ドラフトありがとうございます！
内容の方更新しましたので、今週のpotatotips34 後、木曜日あたりで公開しようと思います。

**Comment by tokorom** [comment]
@horimislime ありがとうございます！よろしくお願いいたします :bow:

**Comment by horimislime** [comment]
@tokorom 
公開しました！🚀 
http://potatotips.connpass.com/event/43344/

**Comment by tokorom** [comment]
@horimislime １点お願いがあります。

LTの最初 or 最後 or 休憩時間あたりで、try! Swift の告知を数分入れさせていただけないでしょうか。
必須事項ではありませんのでむずかしければお断りください。

**Comment by horimislime** [comment]
@tokorom 
了解です、告知 🙆 です！

**Comment by tokorom** [comment]
@horimislime ありがとうございます！

**Comment by tokorom** [comment]
@horimislime 明日のご開催、お願いいたします :bow:

遅くなりましたが、

https://github.com/potatotips/potatotips/wiki/potatotips-35

で発表順を決定させていただきました。
御社メンバーやゲスト発表者などございましたら、こちらに追記をお願いいたします。

**Comment by horimislime** [comment]
@tokorom 
ありがとうございます！追記させて頂きます。明日はよろしくお願いいたします 🙏
