### ISSUE TITLE
2017年3月のpotatotips （Origami様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#32]
確定

Origami 様。
担当 @ikamoon さん

**Comment by tokorom** [comment]
@ikamoon 来月のご開催、よろしくお願いいたします :bow:

本日、イベントページのドラフトを作成いたします。まずは日程のご調整をよろしくお願いいたします。

**Comment by tokorom** [comment]
まずはconnpassのイベントページのドラフトを作成しました！ https://connpass.com/event/50155/edit/

@ikamoon さんだけ管理者に追加しております。

**Comment by ikamoon** [comment]
@tokorom ありがとうございます！

日時と場所を以下でお願いできればと思います。

日時：
2017年2月22日(水)
8:30 開場

場所：
表参道オフィス
〒107-0062 東京都港区南青山5丁目2番1号 NBF ALLIANCE 201 
http://static.origami.co/map.pdf

**Comment by tokorom** [comment]
@ikamoon 日程のご調整ありがとうございます！

> 8:30 開場

は 18:30 開場、19:00開始で大丈夫ですかね？

**Comment by tokorom** [comment]
@ikamoon イベントページのTODOを整理させていただきました :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（管理者）を必要に応じて追加をお願いします
- [ ] 開催日時や場所などに変更がございましたら更新をお願いします
- [ ] Event Imageの登録（特に決まりはありません。御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います。）
- [ ] 募集枠を会場や御社ご状況に合わせてご変更ください
- [ ] Description部分に変更の必要な箇所がありましたら編集をお願いします（TODOマークを付けております）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 更新が終わりましたら良きタイミングで公開いただいて大丈夫です

**Comment by ikamoon** [comment]
> は 18:30 開場、19:00開始で大丈夫ですかね？

1が抜けておりました。大丈夫ですmm

**Comment by tokorom** [comment]
@ikamoon すみません。後追いで申し訳ありませんが、connpassのイベントページに

```
# 申し込み条件

connpassのアカウントに対して、Twitter/Facebook/Githubのいずれか **iOS/Androidに関わる活動が確認できるアカウント** の連携をお願いします。
アカウントの連携がない、もしくは連携されていてもiOS/Androidに関わる活動が確認できない場合、事前告知なく申し込みをキャンセルさせていただくことをご了承願います
```

という項目を追加させていただきました。
これは、俗にいうタダ飯おじさん対策で、今回は後から条件を加えたため「明らかにNGな参加者のみ」事前に強制キャンセルをさせていただきます（現在、ブラックリストを取得中です）。こちらは所のほうで対応させていただきます。

**Comment by ikamoon** [comment]
@tokorom 承知しました。ご対応をありがとうございます。

**Comment by tokorom** [comment]
@ikamoon 

当日の発表順をランダムで決定し、

https://github.com/potatotips/potatotips/wiki/potatotips-38

に記載をさせていただきました。
御社からのご発表者やゲストのかたなどいらっしゃいましたら、こちらに追記をお願いします :bow:
