### ISSUE TITLE
2017年7月のpotatotips （クックパッド様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#36]

**Comment by giginet** [comment]
大分先になってしまいますが、弊社（クックパッド）でやるのは如何しましょうか
会場など提供できると思います

**Comment by tokorom** [comment]
@giginet ありがとうございます！ぜひお願いいたします :bow:

**Comment by giginet** [comment]
そろそろ日程だけでも決めましょうか

**Comment by tokorom** [comment]
@giginet 

よろしくお願いします！

直近の6月の開催が6月19日(月)になります。

日程に関しては7月の中旬〜後半あたりでご調整お願いいたします。
所の参加は必須ではありませんので、御社のご都合の良い日程でご決定ください。

**Comment by giginet** [comment]
現在日程調整中ですので、来週中には候補日をお伝えいたします

**Comment by giginet** [comment]
7/25（火）か26（水）のどちらかで、所さんのご都合が付く日でお願いしてもよろしいでしょうか。
お酒と軽食もご用意できます。

**Comment by tokorom** [comment]
@giginet ありがとうございます！25,26ともに所参加可能です :bow:

**Comment by giginet** [comment]
でしたら、7/25日(火) 19:30~ 定員50名行きましょう。
会場など確保いたします

**Comment by tokorom** [comment]
ご調整ありがとうございます！よろしくお願いいたします :bow:

**Comment by giginet** [comment]
しっかり準備ができておらず最初グダってしまいましたが、結果的には良い会になったと思います。
ありがとうございました 🎉
