### ISSUE TITLE
2017年8月のpotatotips （マネーフォワード様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#37]
マネーフォワード様 予約
担当：@koutalou さん

**Comment by yukiasai** [comment]
担当 @koutalou さんに変更させていただきますね！

**Comment by tokorom** [comment]
@koutalou さん、よろしくお願いいたします :bow:

**Comment by tokorom** [comment]
@koutalou 本件、連絡が滞っており申し訳ありません。8月のご開催、問題ないでしょうか。まずは開催日のご決定をお願いいたします :bow:

**Comment by koutalou** [comment]
まずい、まず日程を決めます:bow:

**Comment by tokorom** [comment]
@koutalou 連絡が遅れ失礼しました。ちょうど9月のpotatotipsがお休み予定だったので、場合によっては9月に設定いただいても大丈夫です！

**Comment by koutalou** [comment]
@tokorom 8/28-9/1の週は丸々一週間抑えられそうです。 @tokorom さんの予定的に一番良さそうな日程で大丈夫です！

**Comment by koutalou** [comment]
それより前は厳しそうですが、後ろの週にズラしたりするのも大丈夫です

**Comment by tokorom** [comment]
@koutalou ありがとうございます！ではお言葉に甘えさせていただき、私が都合の良い 8/29（火）にてご調整お願いいたします :bow:

**Comment by koutalou** [comment]
@tokorom 承知しました！このあとどのようにことを運べば良いでしょうか？会場の準備や食べ物飲み物の準備はこちらで手配する想定でいます！

**Comment by tokorom** [comment]
@koutalou 

ありがとうございます！
取り急ぎ https://github.com/potatotips/potatotips で「主催者様にお願いすること」以降をご一読お願いします :bow:

近日中にconnpassのイベントページ作成してこちらでmentionさせていただきます！

**Comment by tokorom** [comment]
@koutalou 

connpassのイベントページのドラフトを作成し、 koutalouさんを管理者として追加させていただきました。

https://connpass.com/event/63472/edit/

お手数ですが、以下、ご確認お願いいたします。

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠を会場や御社ご状況に合わせてご変更ください
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips

**Comment by koutalou** [comment]
@tokorom ちょっとこちらの都合で大変申し訳ないのですが、8/29が別の会社のイベントでどうしても使わせて欲しいという要望があり別の日程に変更させていただけないでしょうか。。
大変申し訳ありません 🙇 🙇 

8/28(月), 8/31(木), 9/1(金)ですと大丈夫なのですがいかがでしょうか。

確認事項についても確認中です 🙇

**Comment by tokorom** [comment]
@koutalou かしこまりました！では、8/28（月）でお願いします！

**Comment by koutalou** [comment]
@tokorom ありがとうございます！！ 🙇

**Comment by koutalou** [comment]
@tokorom 対応遅くなりました！こちらで大丈夫なのですが、公開はいつでも良いでしょうか？

**Comment by tokorom** [comment]
@koutalou ありがとうございます！公開いつでもOKですので良きタイミングで公開お願いいたします :bow:

**Comment by koutalou** [comment]
夕方が良さそうという噂を聞いたので平日夕方に公開しました！

**Comment by tokorom** [comment]
@koutalou 

connpassのほうでの発表者へのメール連絡、対応が遅くなり大変申し訳ありませんでした。

先ほど、
- connpassのPresenterに発表者を追加
- GitHubのpotatotipsのメンバーに発表者を追加
- connpassから管理者・発表者に絞ってメール通知
をさせて頂きました :bow:

明日当日のpotatotipsのご運営よろしくお願い申し上げます :bow:

**Comment by koutalou** [comment]
@tokorom いえいえ、ご対応ありがとうございました。
昨日のPotatotipsはとても盛況だったように感じます、ありがとうございます😃
是非またお願いしたいと思いますので、どうぞよろしくお願いいたします 🙇

**Comment by tokorom** [comment]
@koutalou 

potatotipsのご運営ありがとうございました！！

まずお詫び申し上げないといけないのですが、私のカレンダーに変更前の実施日の8/29（火）がpotatotips実施日と登録したままになっており、じつは、今晩の実施と今まで勘違いしておりました。

私が不参加のケースもちょくちょくあるのですが、今回は参加の予定だったにも関わらず、私のミスでの不参加となってしまいました。
本来であれば現地に伺ってツイートの対応などすべきだったのですが大変申し訳ありませんでした。

これにこりずまた次の機会もどうぞよろしくお願いいたします :bow:

**Comment by koutalou** [comment]
@tokorom あ、そうだったんですねw
もしかして忙しかったのかなとか思っていたので大丈夫でした 😃 
いつも運営・窓口の対応お疲れ様です。
是非また次の機会によろしくお願いします 😆
