### ISSUE TITLE
2017年10月のpotatotips （エウレカ様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#39]
## 主催者様

エウレカ様（担当： 長坂さん @satoshin21   ）

## 開催日

- 2017年10月中旬（未定）
- 18:30 開場 19:00 開始

## 場所

- エウレカ様オフィス（未定）

**Comment by satoshin21** [comment]
@tokorom 
お久しぶりです！
本件、#44を弊社で執り行わせていただく件ですが、日程調整をさせて頂きたくご連絡致します。
10月中旬ですと、

・10/16 18:30〜
・10/23 18:30〜
・10/24 18:30〜
・10/25 18:30〜

あたりでお願いしたいのですが、 @tokorom sanのご予定などはいかがでしょうか？

また、弊社セミナースペースのキャパシティ的に、人数は70人ぐらい(登壇者含)まで対応可能です。
よろしくお願い致します。

**Comment by tokorom** [comment]
@satoshin21 ご調整ありがとうございます！

所の第一希望は「10/25 18:30〜」ですが、他日程でも全く問題ありませんので、御社の良き日程をご指定ください。

**Comment by satoshin21** [comment]
@tokorom 
ご確認ありがとうございます！

「10/25 18:30〜」にて会場を押さえさせて頂きました。
こちらの日程で進めさせて頂ければと思います。

**Comment by tokorom** [comment]
@satoshin21

connpassのイベントページのドラフトを作成し、 satoshin21さんを管理者として追加させていただきました。

https://connpass.com/event/68024/edit/

お手数ですが、以下、ご確認お願いいたします。

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips

**Comment by satoshin21** [comment]
@tokorom 
こちらイベントページの追記をしました！公開してしまってよいでしょうか？

**Comment by tokorom** [comment]
@satoshi0212 

ありがとうございます！
よきタイミングで公開してしまってください :bow:

**Comment by satoshin21** [comment]
@tokorom 
こちら公開しました！当日もよろしくお願い致します😆
ちなみに、弊社の人間も1~2名ほどLTさせて頂きたいのですが、別枠で参加可能でしょうか？

**Comment by tokorom** [comment]
@satoshin21 

各種ご調整＆ご対応ありがとうございました。

> ちなみに、弊社の人間も1~2名ほどLTさせて頂きたいのですが、別枠で参加可能でしょうか？

はい！
御社メンバーおよびゲストのLTなどは御社裁量にてご自由に差し込みください :bow:
