### ISSUE TITLE
2017年11月のpotatotips （Recruit Marketing Partners様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#40]
Recruit Marketing Partners様 ご予約

**Comment by yukiasai** [comment]
@tokorom こんにちは！だいぶ先の話になりますが、こちらRecruit Marketing Partnersで主催させて頂いてもよろしいでしょうか？

**Comment by tokorom** [comment]
@yukiasai もちろんです！ぜひお願いいたします :bow:

**Comment by yukiasai** [comment]
ありがとうございます！それでは引き続きよろしくお願いします 🙇

**Comment by yukiasai** [comment]
こちらもそろそろ日程決めないとですね！週明けには候補日をお送りいたします。

**Comment by tokorom** [comment]
@yukiasai ありがとうございます！よろしくお願いいたします。

**Comment by yukiasai** [comment]
@tokorom 日程調整の件ですが、以下のいずれかの日程でお願いしたいのですが、所さんの予定はいかがでしょうか？？

* 11/20 (月)
* 11/21 (火)
* 11/22 (水)

**Comment by yukiasai** [comment]
↑日付間違えていたので修正しました 🙇

**Comment by tokorom** [comment]
@yukiasai 日程候補ありがとうございます！

所はいつでも大丈夫です。
（家庭の事情で19:00に間に合わないかもしれないのですが、その場合は申し訳ありませんが遅れての到着とさせてください）

強いていえば

> 11/29 (水) 18:30~

希望です :bow:

**Comment by yukiasai** [comment]
@tokorom 11/29 (水) に会場とれましたので、 18:30開場 19:00開始でお願い致します！

**Comment by tokorom** [comment]
@yukiasai 日程のご調整ありがとうございました！

現在、こちらで募集ページのドラフトを作成しております。

https://connpass.com/event/70161/edit/

開催場所は、京橋トラストタワーでよろしいでしょうか？

**Comment by kboy-silvergym** [comment]
横から失礼します。筋肉.swift主催のkboy(藤川)です。

筋肉.swiftが11月29日に開催なので、できれば11月29日以外ですと幸いです。（遅くてすみません）
ご検討のほど宜しくお願い致します🙇
https://kinniku-swift.connpass.com/event/69438/

**Comment by yukiasai** [comment]
@tokorom connpass有難うございます 🙇 別の拠点になりますので、開催場所はこちらで埋めさせていただきます！

**Comment by yukiasai** [comment]
@kboy-silvergym ご指摘有難うございます！人気イベント被ってしまうともったいないですよね。
@tokorom 最初に提示した日程の中で再調整させていただいても構いませんでしょうか？

**Comment by tokorom** [comment]
@kboy-silvergym @yukiasai さんにご調整いただき、11/28（火）で最終決定しました！

**Comment by tokorom** [comment]
@yukiasai 

こちらが募集ページ（connpass）関連のお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips

**Comment by yukiasai** [comment]
@tokorom ありがとうございます！チェックリスト&社内確認が完了しましたら公開させていただきます 💪 もう少々お待ち頂ければと思います 🙇

**Comment by yukiasai** [comment]
@tokorom connpass公開しました！https://potatotips.connpass.com/event/70161/

**Comment by tokorom** [comment]
@yukiasai ありがとうございました！
