### ISSUE TITLE
2017年12月のpotatotips （ディップ株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#41]
ご担当者：Kazuaki Kuriuさん

**Comment by kurikazu** [comment]
お世話になります。
いくつか日程を決めてご連絡しますが、年末ということもあり遅くても 12月18日の週 になるかと思います。
11月の開催が月末なので、少しインターバルが短くなってしまいますが、問題ないでしょうか。

**Comment by tokorom** [comment]
@kurikazu ご調整ありがとうございます！

はい、問題ありません。
これまでの運営で調整しきれずにインターバルが短い形になってしまい申し訳ありません。

**Comment by kurikazu** [comment]
@tokorom 承知しました。下記の日程で所さんのご都合はいかがでしょうか？？
・12/11 (月)
・12/13 (水)
・12/18 (月)
各日とも19:00開場で考えております。

**Comment by tokorom** [comment]
@kurikazu ありがとうございます！お返事遅くなり申し訳ありません。

どの日程も大丈夫ですので御社ご都合に合わせてご決定ください。

**Comment by kurikazu** [comment]
@tokorom ありがとうございます。では 12/18（月）で進めたいと思います。
どうぞよろしくお願いいたします。

**Comment by tokorom** [comment]
@kurikazu 

こちら遅くなり申し訳ありませんが、connpassで募集ページのドラフトを作成し、管理者にkurikazuさんを追加させていただきました。

https://connpass.com/event/73328/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips

**Comment by kurikazu** [comment]
@tokorom ドラフトありがとうございます。必要事項を記載しました。
問題なければ、本日のpotatotips中に公開したいと思います

**Comment by tokorom** [comment]
@kurikazu ありがとうございます！！！！問題ありませんので良きタイミングにて公開お願いいたします :bow:

**Comment by tokorom** [comment]
@kurikazu 本日potatotips終了後のツイートでの周知のため、私のほうで公開させていただきました :bow:

**Comment by kurikazu** [comment]
@tokorom ありがとうございますmm
