### ISSUE TITLE
2018年4月のpotatotips （Wantedly様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#45]

**Comment by tokorom** [comment]
@hedjirog 2018年4月でおさえさせていただきました！

**Comment by luvtechno** [comment]
@hedjirog そろそろ日付決めましょうか

**Comment by MasahiroInou** [comment]
@luvtechno 
4/19で決まりました！

**Comment by tokorom** [comment]
4/19 うけたまわりました！

**Comment by tokorom** [comment]
@hedjirog 

connpassに募集ページのドラフトを作成し、hedjirogさんを管理者として追加させていただきました。

https://connpass.com/event/82476/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by hedjirog** [comment]
@tokorom ありがとうございます！確認します！

**Comment by hedjirog** [comment]
公開しました！ https://potatotips.connpass.com/event/82476/

**Comment by tokorom** [comment]
@hedjirog 来週木曜、potatotips運営よろしくお願いいたします！

先ほど、ランダムに発表順を決定し、

https://github.com/potatotips/potatotips/wiki/potatotips-50

に記載をさせていただきました。
御社からの発表者、ゲストなどの追加がございましたらこちらに追記をお願いいたします。
