### ISSUE TITLE
2018年10月のpotatotips （ヤフー様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#51]
ご担当者様：ヤフー 熊本さん @kumamotone 
場所：ヤフーLODGE

**Comment by kumamotone** [comment]
@tokorom ヤフーの熊本です。
こちらぜひ立候補させていただければと思うのですが、いかがでしょうか…！

場所は、2017年2月(https://github.com/potatotips/potatotips/issues/31) ,2017年6月(https://github.com/potatotips/potatotips/issues/35) のpotatotipsと同様にヤフーLODGEを想定しております。

**Comment by tokorom** [comment]
@kumamotone 立候補ありがとうございます！
ぜひお願いいたします。

このIssueにkumamotoneさんをassignしたく、Githubのpotatotipsチームへの招待を送らせていただきます。お手数ですがJoinをお願いいたします。

**Comment by kumamotone** [comment]
前回のpotatotipsのときにinviteいただいていたのに今気づきました…！ｗありがとうございます！　Joinさせていたきました

**Comment by tokorom** [comment]
@kumamotone ありがとうございます！assignさせていただきました 🙇

**Comment by kumamotone** [comment]
@tokorom そろそろ何かと進めて行こうと思っておりますー
候補日なのですが、9月はiOSのイベントが多く、10月末はdroidconがあるので、
間を取って 10/9(火) か 10/10 (水) あたりのご都合はいかがでしょうか

**Comment by tokorom** [comment]
@kumamotone スピーディなご対応ありがとうございます！

10/9(火) か 10/10 (水)どちらでも大丈夫ですので御社ご都合に合わせてご決定ください。

**Comment by kumamotone** [comment]
@tokorom ありがとうございます！調整して再度ご連絡いたしますー

**Comment by tokorom** [comment]
@kumamotone 開催日のご決定＆諸処のご準備ありがとうございます！！

以下、connpassの募集ページのドラフトを作成し、kumamotoさんを管理者として追加させていただきました。

https://connpass.com/event/100763/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by tokorom** [comment]
@kumamotone 

遅くなってしまい申し訳ありません。

- 発表枠の参加者をconnpass上でも発表者として追加
- 初参加のかたをGitHubのpotatotipsに招待
- 発表順をランダムに決定し https://github.com/potatotips/potatotips/wiki/potatotips-55 に記載
- 御社からの発表者の皆様を先頭に追加

させていただきました。
これから、発表枠での参加の皆様にメール通知をさせていただきます。
