### ISSUE TITLE
2018年11月のpotatotips （SmartNews様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#52]
ご担当者様：SmartNews 荒巻さん @firewood

**Comment by tamaki-shingo** [comment]
@tokorom Origamiの玉城です。

立候補させてください。よろしくお願いいたします。

**Comment by tokorom** [comment]
@tamaki-shingo 玉城さん、ありがとうございます。ぜひお願いいたします！

さっそく予約を入れさせていただきました。

よろしければこちらの

**Comment by tamaki-shingo** [comment]
Joinしました！

**Comment by tokorom** [comment]
@tamaki-shingo ありがとうございます！早速assignさせていただきました。しばらく先の話になってしまいますがよろしくお願いいたします。

**Comment by tamaki-shingo** [comment]
申し訳ありません、弊社都合でオフィススペースでの夜間のイベント開催が出来なくなってしまい本件キャンセルさせて頂きたいのですが可能でしょうか？

**Comment by firewood** [comment]
SmartNewsの荒巻です。もし可能でしたら弊社でホストしたく、よろしくお願いします。

**Comment by tokorom** [comment]
@tamaki-shingo うけたまわりました。またご機会がありましたらお願いします。

@firewood カバーいただき助かります！ぜひよろしくお願いいたします 🙇

**Comment by firewood** [comment]
@tokorom そろそろ準備を考えておりまして、11/15 (木) はご都合いかがでしょうか。

**Comment by tokorom** [comment]
@firewood ありがとうございます！11/15 (木) にてぜひお願いいたします。

**Comment by firewood** [comment]
@tokorom 会場を確保しましたので、11/15 (木)で仮ページの作成をお願いできますでしょうか。

**Comment by tokorom** [comment]
connpassに仮ページを作成し、 @firewood  さんを管理者として追加させていただきました。

https://connpass.com/event/104242/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by tokorom** [comment]
@firewood お手数おかけしますがconnpassの募集ページの件よろしくおねがいします 🙇

**Comment by tokorom** [comment]
@firewood 

connpassのご対応ありがとうございました！

さきほど、 https://github.com/potatotips/potatotips/wiki/potatotips-56 に発表順を記載し、発表者の皆様にメール通知させていただきました。

もし御社メンバーやゲストからのご発表がございましたら、こちらに追記をお願いいたします。

それでは、来週11/15 (木) よろしくお願いいたします。
