### ISSUE TITLE
2018年12月のpotatotips （アイスタイル様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#53]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- アイスタイル様

### ご担当者様

- 阿保さん @YuyaAbo 

### 開催日時

-

### 会場

-

**Comment by YuyaAbo** [comment]
@tokorom 恐れ入ります。アイスタイルの阿保と申します。
こちらぜひ立候補させていただきたいのですが、いかがでしょうか。

会場はアイスタイル本社となります。

**Comment by tokorom** [comment]
@YuyaAbo 返信遅れまして申し訳ありません！ぜひ宜しくお願い致します。

**Comment by YuyaAbo** [comment]
@tokorom ありがとうございます！
半年先ですが、会場確保等を粛々と進めます。

また近くなりましたらよろしくお願いいたします。

**Comment by YuyaAbo** [comment]
@tokorom こちら、12/18(火)での開催はご都合いかがでしょうか。

**Comment by YuyaAbo** [comment]
一応12/18で会場(アイスタイル)は確保済みです。

**Comment by tokorom** [comment]
ありがとうございます！ぜひお願いいたします。
イベントページのドラフトも用意させていただきます。

**Comment by tokorom** [comment]
@YuyaAbo 以前にpotatotipsのGithubページへのInvitationを送らせていただき、おそらくhttps://github.com/potatotipsなどからaccept可能かと思います。こちらのIssueにassignさせていただくため、お手数ですがacceptをお願いいたします。

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @YuyaAbo さんを管理者として追加させていただきました。

https://connpass.com/event/109263/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by YuyaAbo** [comment]
@tokorom 

> こちらのIssueにassignさせていただくため、お手数ですがacceptをお願いいたします。

確認しまして、join致しました。

> connpassに募集ページのドラフトを作成し、

ドラフトページありがとうございます！

**Comment by YuyaAbo** [comment]
@tokorom すみません、弊社の都合がありまして、イベントページ公開が11/16(金)以降になります。

**Comment by tokorom** [comment]
@YuyaAbo かしこまりました！まったく問題ありません。

**Comment by YuyaAbo** [comment]
@tokorom イベントページを公開致しました！
https://potatotips.connpass.com/event/109263/

なにか不備等見つけましたらお申し付けください。

**Comment by tokorom** [comment]
@YuyaAbo 

来週のpotatotipsご開催、よろしくお願いいたします。

１点相談なのですが、現在、Androidブログまとめ枠が0人のまま空いてしまっており、もしよろしければiOS/Androidの区分けなしでブログまとめ枠4人の枠として統合させていただこうと思うのですが、いかがでしょうか？

**Comment by tokorom** [comment]
@YuyaAbo 

すみません。このあと、Androidブログまとめ枠に１名入っていただけましたので、上の件は様子を見させてください。

**Comment by tokorom** [comment]
さきほど、

- 発表枠の参加者をconnpass上でも発表者として追加
- 初参加のかたをGitHubのpotatotipsに招待
- 発表順をランダムに決定し https://github.com/potatotips/potatotips/wiki/potatotips-57 に記載
- 発表者の皆様へのメール連絡

させていただきました。

御社からのご発表者やゲスト発表者などございましたら、上記Wikiに追記をお願いいたします。

**Comment by YuyaAbo** [comment]
@tokorom 

すみません、返信遅れました。上記の件承知しました。ありがとうございます！

弊社からはAndroid Tips発表枠として2名、一般と同じように参加致します。(これ含めて現在5名)
発表タイトルが決まっていれば更新するよう伝えておきます。

それでは明日、よろしくお願い致します。

**Comment by tokorom** [comment]
@YuyaAbo ご対応ありがとうございます！
本日のご開催よろしくお願いいたします。
