### ISSUE TITLE
2019年2月のpotatotips （GREE様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#55]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- GREE様

### ご担当者様

- @DayBySay さん

### 開催日時

- 2/28（木）

### 会場

- 六本木ヒルズ GREE様オフィス

**Comment by DayBySay** [comment]
@tokorom 
お疲れ様です。本日はありがとうございました。
ぜひ弊社GREE（六本木ヒルズ）で開催させて頂ければと思います！
よろしくお願い致します。

**Comment by tokorom** [comment]
@DayBySay ありがとうございます！ぜひお願いいたします。

お手数ですが、potatotipsチームへのInvitationを送らせていただきましたのでご承認お願いいたします（このIssueにassignさせていただくためです）

**Comment by DayBySay** [comment]
@tokorom 
チーム参加させて頂きました〜。

**Comment by tokorom** [comment]
@DayBySay assignさせていただきました！しばらく先になってしまいますが、よろしくお願いいたします。

**Comment by DayBySay** [comment]
@tokorom 
お返事遅くなってもうしわけありません。
日程ですが、2/28（木）で考えております。
ドラフトの方よろしくお願いいたします。

**Comment by tokorom** [comment]
@DayBySay ご連絡ありがとうございます！今月末のご主催よろしくお願いいたします。

connpassに募集ページのドラフトを作成し、DayBySayさんを管理者として追加させていただきました。

https://connpass.com/event/119277/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by DayBySay** [comment]
@tokorom 
公開しましたm(_ _)m

**Comment by tokorom** [comment]
@DayBySay ありがとうございます！ツイートなどさせていただきます。
