### ISSUE TITLE
2019年3月のpotatotips （ZOZOテクノロジーズ様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#56]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- 株式会社ZOZOテクノロジーズ様

### ご担当者様

- 堀江さん @horie1024 

### 開催日時

- 3/27（水）18:30開場 19:00開始

### 会場

- ZOZOテクノロジーズ青山オフィス

**Comment by horie1024** [comment]
@tokorom
スタートトゥディテクノロジーズの堀江です。いつもお世話になっております。
2019年3月のpotatotipsをスタートトゥディテクノロジーズ青山オフィスで開催したいのですが、可能でしょうか？

よろしくお願いします。

**Comment by tokorom** [comment]
@horie1024 ありがとうございます！遠い日付になってしまいますが、ぜひ、お願いいたします。

**Comment by horie1024** [comment]
@tokorom はい！よろしくお願いしますー！

**Comment by horie1024** [comment]
@tokorom 
社名が変更となり、10/1より株式会社ZOZOテクノロジーズとなりました。
引き続きよろしくお願いいたします。

**Comment by tokorom** [comment]
@horie1024 社名変更おめでとうございます！わかりやすくて良い名前ですね。

Issueタイトルなどでの表記も更新させていただきました。

**Comment by tokorom** [comment]
@horie1024 3月のご開催よろしくお願いいたします。

2月の開催ですが、2/28（木）となりました。それに合わせるとすると3月後半になりそうですが、try!Swiftが3月20日(水) – 3月22日(金)となっており、その翌週あたりが候補になりそうでしょうか。
お手数ですが御社ご状況に合わせて日程のご決定をお願いいたします。

potatotipsですが4月はお休み予定にしておりますので、場合によっては4月の前半でもかまいません。

**Comment by horie1024** [comment]
@tokorom 返信が遅れてしまいすみません。社内で検討させていただき、日程を決定させていただきますね。

**Comment by tokorom** [comment]
@horie1024 

すみません。１点相談があります。

もし3月末にご実施いただけるようでしたら、ちょうどそのタイミングでBitriseの皆様がtry!Swiftのために訪日しているとのことで、日程があえばpotatotipsでの発表の機会をもらえればというご依頼をいただきました。
もちろん3月の開催はZOZOテクノロジーズ様がご主催者ですのでお断りいただいて構わないのですが、もし、Bitriseの社員さんをゲスト発表者として追加させていただくことが可能でしたらご教示お願いします。
（ここでのやりとりはオープンになってしまうので、場合によっては別のところでやりとりしましょう）

**Comment by horie1024** [comment]
@tokorom 
承知しました！僕としてはBitriseの社員さんにぜひ発表してもらいたいので調整させてください:+1:

**Comment by horie1024** [comment]
@tokorom 
3/25から3/28の間で開催日程を検討しているのですが、Bitriseさんの都合の良い日時等はわかりますでしょうか？

**Comment by tokorom** [comment]
@horie1024 ご調整ありがとうございます！Bitriseさんに日程伺っていますので回答お待ち願います。

**Comment by tokorom** [comment]
@horie1024 Bitriseさんから２７日であれば参加可能とご連絡いただきました！ご調整よろしくお願いいたします。

**Comment by horie1024** [comment]
@tokorom 確認していただきありがとうございます、27開催で進めますね！

**Comment by horie1024** [comment]
@tokorom 27日開催で決定とさせてください！よろしくお願いします！

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @horie1024  さんを管理者として追加させていただきました。

https://connpass.com/event/123002/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by horie1024** [comment]
@tokorom 
2点ほど質問があります。

- iOS、Androidで弊社枠として1枠づつ登壇枠をいただくことは問題ないでしょうか？
- Bitriseさんの登壇時間はどの程度確保すれば良いでしょうか？

確認、よろしくお願いします。

**Comment by tokorom** [comment]
@horie1024 もちろんです！必須ではないですが、

LTの一人目、二人目を御社枠としていただき、三人目からをBitriseさん枠としていただき、以降通常LTという流れにしていただくのがスムーズかなと考えております。

Bitriseさんのメンバー数（iOS/Android両方あるか、まとめて１枠で良いかなど）について確認させていただきますので、そちらはお待ち願います。

**Comment by horie1024** [comment]
@tokorom ありがとうございます！

**Comment by tokorom** [comment]
@horie1024 

Bitriseさんからご返信いただきました。BitriseさんLTですが、御社LTに続く形で、

- iOS向け LT 5分
- Android向け LT 5分

を差し込みお願いいたします！

**Comment by horie1024** [comment]
@tokorom 
承知しました！一般のiOS、AndroidLT参加枠の募集を5名にしますね。

**Comment by horie1024** [comment]
@tokorom 
こんな感じで公開しようと思います。「Bitrise社が特別参加」という節を追加しています。一応ご確認頂けるとありがたいですー！

https://potatotips.connpass.com/event/123002/preview/

**Comment by tokorom** [comment]
@horie1024 確認させていただきました。各種ご調整ありがとうございます！
内容問題せんので良きタイミングで公開お願いします 🙇

**Comment by horie1024** [comment]
@tokorom 確認ありがとうございます！今日の夕方には公開しますね

**Comment by horie1024** [comment]
@tokorom 先ほど公開しました！

**Comment by horie1024** [comment]
@tokorom 
お疲れ様です！明日はよろしくお願いします。

明日なのですが、僕が家庭の事情で参加できないため弊社広報の坂井が代わりに司会を担当する予定です。

また、potatotips終了後にアンケートを実施したいのですが、これは弊社から参加者のみなさんに送らせて頂いても問題ないでしょうか？

**Comment by tokorom** [comment]
@horie1024 

当日、お会いできないのが残念ですが、ご状況承りました！
アンケート実施につきましても問題ありませんおで、御社からご送付いただきますようお願いいたします。

**Comment by horie1024** [comment]
@tokorom 
承知しました！

**Comment by horie1024** [comment]
@tokorom 
度々申し訳ないのですが、BitriseさんのLTは英語でしょうか？

**Comment by tokorom** [comment]
@horie1024

はい！英語になります。
通訳が入らない前提で英語でのLTをお願いしております（登壇いただくかたがEnglish onlyです）

会場入りや現地でのやりとりなどは日本法人のかたにサポートいただけるはずです。（念のため最終確認させていただきます）

**Comment by horie1024** [comment]
@tokorom 
承知しました🙆

**Comment by horie1024** [comment]
@tokorom 

本日はありがとうございました！

**Comment by tokorom** [comment]
@horie1024 

こちらこそありがとうございました！とても素敵なオフィスでした。事前のご調整および当日の会場や進行など潤沢にご準備いただき感謝です。
またご機会がありましたら是非お願いいたします。
