### ISSUE TITLE
2019年6月のpotatotips （DMM様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#59]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- DMM様

### ご担当者様

- 多和田さん @yuta24 

### 開催日時

- 6/18（火）予定

### 会場

- DMM様 六本木オフィス

### イベントページ

https://connpass.com/event/129207/edit/

**Comment by yuta24** [comment]
@tokorom 

初めまして。
DMM の多和田と申します。
2019年6月の potatotips を弊社六本木オフィスで開催できればと考えております。いかがでしょうか？

どうぞよろしくお願いいたします。

**Comment by tokorom** [comment]
@yuta24 ご連絡ありがとうございます！6月のご開催、少し先になってしまいますがぜひお願いいたします。

早速ですが、このIssueにDMM様のお名前を入れさせていただきました。

また、 @yuta24 さんをassignさせていただきたく、 https://github.com/potatotips/potatotips への招待を送らせていただきました。お手すきの際にご参加をお願いいたします。

**Comment by yuta24** [comment]
@tokorom 

ご快諾いただき、ありがとうございます！チームへ参加させていただきました。
あと、お願いなのですが、弊社の会議室確保の都合上、5月の開催日程が決まり次第、6月の開催日程を詰めさせていただければ幸いです。

引き続き、よろしくお願いいたします。

**Comment by tokorom** [comment]
@yuta24 ご参加ありがとうございます！それでは、5月の日程が決まり次第、またmentionさせていただきます。

**Comment by yuta24** [comment]
承知しました。
どうぞよろしくお願いいたします！

**Comment by yuta24** [comment]
@tokorom 

2019年5月開催の potatotips が公開されていたので、6月の弊社開催の日程を決められたらと考えています。こちらから日程候補日を提示する形でよろしいでしょうか？

**Comment by tokorom** [comment]
@yuta24 

はい！御社ご都合に合わせてご決定ください。
よろしくお願いします。
（5月の日程が決まり次第と書いていたにも関わらず...）連絡できておらず失礼しました。

**Comment by yuta24** [comment]
@tokorom 

いえいえ、大丈夫です！ 👌 
日程ですが、 6/18 でお願いしたいと思っています。どうぞよろしくお願い致します！

**Comment by tokorom** [comment]
うけたまわりました！6/18よろしくお願いいたします。
近日、募集ページのドラフトを作成いたします。

**Comment by yuta24** [comment]
承知しました！
引き続き、よろしくお願い致します。

**Comment by tokorom** [comment]
@yuta24 

connpassに募集ページのドラフトを作成し、 多和田さんを管理者として追加させていただきました。

https://connpass.com/event/129207/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by yuta24** [comment]
承知しました！
お願い事項リストの記載、ありがとうございます。
上記のリストの事項を完了しましたら、公開させていただきます。

**Comment by yuta24** [comment]
@tokorom 

公開しました！

**Comment by tokorom** [comment]
@yuta24 ありがとうございます！！！！来月のご開催、よろしくお願いいたします。

**Comment by tokorom** [comment]
@yuta24 来週のご開催よろしくお願いいたします。

さきほど、LT発表順をランダムに決定し、

https://github.com/potatotips/potatotips/wiki/potatotips-62

に記載し、発表者の皆様に通知させていただきました。
御社からのLTご発表などございましたら、お手数ですがこちらに追記をお願いします。

**Comment by yuta24** [comment]
@tokorom 

こちらこそ、よろしくお願いいたします！
弊社からの登壇2名を追記させていただきました。入館方法の案内は週明け月曜に送付させていただきます。
