### ISSUE TITLE
2019年8月のpotatotips （Repro様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#61]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- Repro株式会社様

### ご担当者様

- 長峯さん @konyavic 
- Markusさん @mw99

### 開催日時

- 8月未定

### 会場

- Repro様オフィス

**Comment by konyavic** [comment]
@tokorom 
はじめまして、Repro株式会社の李です。
弊社は5月から新しいオフィスフロアを開設する予定ですので、ぜひ8月の会場を提供できればと考えております。
宜しくお願いいたします。

**Comment by tokorom** [comment]
@konyavic ご連絡ありがとうございます！新オフィスのご開設おめでとうございます。

さっそく本Issueに予約を入れさせていただき、 @konyavic さんをassignさせていただきました。

少し先になりますが是非よろしくお願いいたします。

**Comment by konyavic** [comment]
早速のご返信ありがとうございます！よろしくお願いいたします！

**Comment by konyavic** [comment]
@tokorom 

そろそろ1.5ヶ月前が近付いてきたので、準備を開始します。
日程及び人数は近日中にFIXする予定ですが、
担当は下記の2名に変更させてください :bow:

@mw99 @hiro-nagami

**Comment by tokorom** [comment]
@konyavic ご連絡ありがとうございます！

まずは @mw99 さん、 @hiro-nagami さんのご両名をこちらのIssueにassignさせていただきたく、 https://github.com/potatotips へのInvitationを送らせていただきました。お手数ですがご承認をお願いいたします。

**Comment by hiro-nagami** [comment]
@tokorom  さん初めまして！Reproの長峯と申します。

Invitationありがとうございます。今後は私と@mw99の２人で担当させていただきますので、何卒よろしくお願いいたします 🙇

**Comment by tokorom** [comment]
@hiro-nagami @mw99 こちらこそよろしくお願いいたします 🙇

**Comment by hiro-nagami** [comment]
@tokorom お世話になっております。長峯です。

イベントの開催日程を8/27で、30人程度で進めようと思っています！
何卒よろしくお願いいたします。

**Comment by tokorom** [comment]
@hiro-nagami 

ありがとうございます！それでは１ヶ月半ほど前になりましたら、8/27でconnpassの募集ページのドラフトを作成させていただきます。

１点だけお願いなのですが、8/26から8/29は私が東京不在で当日の参加ができません。
通常、当日にTwitterで「次のLTは〇〇さんで、〇〇です」といったツイートだけさせていただいているのですが、これを御社のどなたかにお願いすることは可能でしょうか。もちろん、これも必須ではありませんのでなくても構いません。

**Comment by hiro-nagami** [comment]
@tokorom 

承知致しました。よろしくお願いいたします！

Twitterの件、こちらで対応させていただくことは大丈夫です。
もし、投稿するときにハッシュタグなどあれば教えていただけると幸いです。
何卒、よろしくお願いいたします。

**Comment by tokorom** [comment]
@hiro-nagami 

ありがとうございます！
ハッシュタグは https://twitter.com/hashtag/potatotips でお願いいたします。

普段はこんな形でツイートしていますが、特に規定などありませんので当日のやりかたについては全てお任せします 🙇 

![image](https://user-images.githubusercontent.com/629993/59571879-22111980-90e4-11e9-8307-684dda396f3e.png)

**Comment by tokorom** [comment]
@hiro-nagami @mw99 

connpassのドラフトページを作成させていただいております。お手数ですが、おふたりのconnpassのアカウント名をご教示ください。

今回、会場は御社オフィス（渋谷区代々木１丁目３６−４ 4F）でよいでしょうか？

**Comment by hiro-nagami** [comment]
@tokorom 

ありがとうございます。connpassのアカウントは@nagami_hiroです。
@mw99 の方は今お休みをいただいているため、後ほどご連絡します。

住所については「東京都渋谷区代々木1丁目36-4 全理連ビル4階」をお使いいただければ幸いです。

何とぞよろしくお願いいたします。

**Comment by tokorom** [comment]
@hiro-nagami ありがとうございます！ドラフトはこちらになります https://connpass.com/event/139008/edit/

**Comment by tokorom** [comment]
以下、connpassの募集ページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by hiro-nagami** [comment]
@tokorom 
承知しました！確認いたします。
ありがとうございます。

**Comment by tokorom** [comment]
@hiro-nagami @mw99 

来週のpotatotipsご主催、よろしくお願いいたします 🙇 

先ほど、発表順をランダムに決定し、

https://github.com/potatotips/potatotips/wiki/potatotips-64

に記載をし、発表者の皆様にメールを送らせていただきました。

https://connpass.com/event/139008/message/48163/

当日、御社からのLTご発表やゲスト発表者様などございましたら、ご自由に上記Wikiに追記をお願いします。

**Comment by hiro-nagami** [comment]
@tokorom ありがとうございます:bow:
