### ISSUE TITLE
2019年10月のpotatotips （ヤフー様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#63]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- ヤフー様

### ご担当者様

- 熊本さん @kumamotone 

### 開催日時

- 10月未定

### 会場

- ヤフーLODGE

### イベントページ

- https://connpass.com/event/145538/

**Comment by kumamotone** [comment]
@tokorom お世話になっております。ヤフーの熊本です。
こちらぜひ立候補させていただければと思うのですがいかがでしょうかｍｍ

場所は 2018月10月 (# 55), 2017年6月(# 35), 2017年2月(# 31) と同様にヤフーLODGEを想定しております。

**Comment by tokorom** [comment]
@kumamotone いつもありがとうございます！ぜひお願いいたします。

**Comment by tokorom** [comment]
@kumamotone potatotips 10月のご開催よろしくお願いいたします 🙇  9月はお休み予定ですので、9月の終わり〜10月のはじめでもかまいません。可能でしたら10月の初旬にご設定いただけると嬉しいです。

**Comment by kumamotone** [comment]
@tokorom お返事遅くなってすみません　承知しました！

**Comment by kumamotone** [comment]
@tokorom お世話になっております　10/1 はいかがでしょうか？

**Comment by tokorom** [comment]
@kumamotone ご調整ありがとうございます！10/1（火）ぜひよろしくお願いいたします。

**Comment by tokorom** [comment]
@kumamotone 

早速、connpassのページのドラフトを作成させていただきました！

https://connpass.com/event/145538/edit/

いつもどおりですが、以下TODOをご確認お願いいたします。

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by kumamotone** [comment]
また遅くなってしまいましたすみません　了解です！ありがとうございます
