### ISSUE TITLE
2019年11月のpotatotips （Yappli様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#64]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- Yappli様

### ご担当者様

- 梶原さん
- 山本さん @SCENEE

### 開催日時

- 2019年11月

### 会場

- https://connpass.com/event/149806/edit/

**Comment by SCENEE** [comment]
@tokorom 
お世話になっております。
こちらをヤプリで開催させていただければと思いますが、いかがでしょうか？
宜しくお願いいたします。

**Comment by tokorom** [comment]
@SCENEE ありがとうございます！ぜひお願いいたします。さっそく予約登録させていただきます。

**Comment by SCENEE** [comment]
予約登録ありがとうございます！時期が近くなりましたら(9/10月ごろ)、ヤプリ梶原より連絡させていただきます。
