### ISSUE TITLE
2019年12月のpotatotips （メルペイ様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#65]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- メルペイ様

### ご担当者様

- kitasuke さん

### 開催日時

- 12/17（火）予定

### 会場

-

### connpassページ

- https://connpass.com/event/152899/edit/

**Comment by kitasuke** [comment]
お久しぶりです。12月はメルカリ開催でも良いですか？

**Comment by tokorom** [comment]
@kitasuke はい！ぜひお願いいたします。

**Comment by kitasuke** [comment]
よろしくお願いします！日程は12/17でお願いします。また日が近くなったら詳細詰めます。

**Comment by tokorom** [comment]
@kitasuke 

12月のご開催、よろしくお願いいたします！
connpassの募集ページですが、11月開催が11/11のため、それが終わったあたりで公開できるとベストかと思います。

取り急ぎ、募集ページのドラフトを作成し、 kitasukeさんを管理者として追加させていただきました。

https://connpass.com/event/152899/edit/

以下、この募集ページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by kitasuke** [comment]
分かりました！11/11に公開できるように進めます。

**Comment by kitasuke** [comment]
connpassページを更新して公開準備出来ました！今日の11月開催分が終わったあたりで公開する予定です。

**Comment by tokorom** [comment]
@kitasuke ありがとうございます！スピーディなご対応感謝です。

**Comment by kitasuke** [comment]
公開しました！

**Comment by tokorom** [comment]
さきほど、発表順をランダムに決定し、 https://github.com/potatotips/potatotips/wiki/potatotips-67 を更新し、発表者の皆様にメール通知させていただきました。
来週12/17（火）のご開催、よろしくおねがいいたします 🙇

**Comment by kitasuke** [comment]
ありがとうございます、よろしくお願いします！
