### ISSUE TITLE
2020年2月のpotatotips （コネヒト様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#67]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- コネヒト株式会社様

### ご担当者様

- 柳村さん @yanamura 

### 開催日時

- 2/12（水）

### 会場

-

**Comment by yanamura** [comment]
@tokorom おつかれさまです！コネヒト株式会社の柳村です。
2月の回ですがぜひ弊社で開催させていただきたいと思いますがいかがでしょうか？

**Comment by tokorom** [comment]
@yanamura ありがとうございます！ぜひよろしくお願いいたします。さっそくassignをさせていただきました。

**Comment by yanamura** [comment]
よろしくおねがいいたします！

**Comment by yanamura** [comment]
@tokorom 日程は2/12(水)にしたいと思います！

**Comment by tokorom** [comment]
ありがとうございます！うけたまわりました。

**Comment by tokorom** [comment]
@yanamura 少し早めですが、connpassに募集ページのドラフトを作成し、 @yanamura さんを管理者として追加させていただきました。

もしかすると12月中に公開しておくほうが入りが多いかもしれません。
もちろん、1月公開でもかまいません。

https://connpass.com/event/160125/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by yanamura** [comment]
@tokorom 承知しました！

**Comment by yanamura** [comment]
@tokorom 募集開始しました！

**Comment by tokorom** [comment]
@yanamura ありがとうございます！

１点だけ、参加者の急なキャンセルで空きが出た場合に当日に飛び込みで参加してくれるかたもおりますので、募集締切を 2/12の19:30に変更させていただいてもよいでしょうか？

**Comment by yanamura** [comment]
締め切り変更しました！

**Comment by yanamura** [comment]
@tokorom 抽選完了しました。
オーディエンス枠にNGかなと思われる方がおられたのですが、[こちら](https://github.com/potatotips/potatotips/wiki/potatotips%E9%96%8B%E5%82%AC-Tips#%E3%82%BF%E3%83%80%E9%A3%AF%E3%81%8A%E3%81%98%E3%81%95%E3%82%93%E5%AF%BE%E7%AD%96)を拝見したところ、こちらの対応は所さんのほうでご対応いただくというかたちで大丈夫でしょうか？

**Comment by tokorom** [comment]
@yanamura 

はい！大丈夫です。ご連絡ありがとうございます。

いま、NG確率の高い応募者さんを１名キャンセル扱いにさせていただきました。

その他、２名ほどTwitterもしくはGitHub連携のない、かつイベント管理・発表の履歴のないかたがオーディエンス補欠にいらっしゃるのですが、こちらは応募履歴を見るかぎり、無作為参加というわけではなさそうですので対応保留とさせていただきました。

**Comment by yanamura** [comment]
ありがとうございました！

**Comment by tokorom** [comment]
@yanamura 

来週 2/12（水）のご開催よろしくお願いいたします！

さきほど、LT発表順をランダムに決定し、発表予定のみなさまにメール通知をさせていただきました。

御社の皆様からのご発表もあるかと思いますので、こちらの１番目、２番目あたりに記載をお願いします。
（いったん２名を入れておりますが、２名以上でももちろん構いません）

https://github.com/potatotips/potatotips/wiki/potatotips-68

**Comment by yanamura** [comment]
@tokorom 
ありがとうございます！
弊社から2名発表者登録しました！
水曜日よろしくお願いいたします〜
