### ISSUE TITLE
2020年3月のpotatotips （クックパッド様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#68]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- クックパッド様

### ご担当者様

- @shanonim さん

### 開催日時

- 3/18（水） 19:30から

### 会場

- クックパッド様恵比寿オフィス

### 募集ページ

- https://connpass.com/event/166452/edit/

**Comment by shanonim** [comment]
@tokorom ご無沙汰しております。クックパッド株式会社の @shanonim です。
2020年3月回、ぜひ弊社で開催させてもらえればと思いますがいかがでしょうか。ご確認おねがいいたします！

**Comment by tokorom** [comment]
@shanonim ご無沙汰しております！potatotips発祥元のクックパッドでのご開催とても嬉しいです。ぜひよろしくお願いします。

**Comment by giginet** [comment]
わいわい

**Comment by tokorom** [comment]
@shanonim そろそろconnpassの募集ページを作成し、2/12（水）のpotatotipsの終了後あたりで公開をしようと考えております。

お手数ですが、ご開催の予定日などご調整お願いします！

**Comment by shanonim** [comment]
確認して調整いたします！

**Comment by shanonim** [comment]
@tokorom 3/16の週でしたら、月〜金どこでも会場使える見込みです。
水曜開催でしたら、3/18(水)が候補となりますが、いかがでしょうか？👀

**Comment by tokorom** [comment]
@shanonim では、3/18（水）でお願いいたします！さっそくconnpassでドラフトを作ります。

**Comment by tokorom** [comment]
@shanonim 

connpassに募集ページのドラフトを作成し、 @shanonim さんを管理者として追加させていただきました。

https://connpass.com/event/166452/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by shanonim** [comment]
現在バナー画像の作成中ですので、公開までもう少々お時間いただけると幸いです:pray:

**Comment by shanonim** [comment]
@tokorom 大変申し訳ありません。昨今の社会情勢: 新型コロナウイルスの流行を受けて、弊社でのイベント開催を3月末まで控えることとなりました・・。
立候補させていただいたせっかくの機会で大変心苦しいのですが、イベント開催の中止をご相談させていただけないでしょうか。。

**Comment by tokorom** [comment]
@shanonim おー、なるほど！うけたまわりました。
また是非次の機会によろしくお願いいたします 🙇

**Comment by shanonim** [comment]
@tokorom 申し訳ありません、ご了承いただきありがとうございます..!
次の機会を調整してまたかならず立候補させていただきますので、引き続きどうぞよろしくお願いいたします。

（確認ののち、issue閉じていただいて大丈夫です :bow: ）
