### ISSUE TITLE
2020年4月のpotatotips （Timers様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#69]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- Timers Inc. 様

### ご担当者様

- @akatsuki174  さん

### 開催日時

- 4/27(月) 20:00

### 会場

- オンライン！

**Comment by jpmartha** [comment]
@tokorom 新型コロナウイルス感染症の終息の見通しが立たないため、4月開催分を中止させていただけないでしょうか？せっかく機会をいただいたのに大変申し訳ありません。

**Comment by tokorom** [comment]
@jpmartha うけたまわりました！現在の状況からするといたしかたなしかと思います。幸い、参加募集もしていない状況ですので全く問題ありません。

またおちついたタイミングでぜひお願いいたします。

**Comment by akatsuki174** [comment]
tokoromさんに直接打診し、Timersにてオンラインpotatotipsの実施を検討中。日程は4/27(月)の予定。

**Comment by tokorom** [comment]
@akatsuki174 ありがとうございます！タイトルやassignなど変えてreopenさせていただきます。
