### ISSUE TITLE
[延期] 2020年5月のpotatotips （オクト様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#70]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- 株式会社オクト様

### ご担当者様

- @daisuke0131 さん

### 開催日時

-

### 会場

-

**Comment by daisuke0131** [comment]
@tokorom お世話になっております。株式会社オクトの @daisuke0131  です。
2020年5月回、ぜひ弊社で開催させてもらえればと思いますがいかがでしょうか。ご検討よろしくお願いいたします！

**Comment by tokorom** [comment]
@daisuke0131 ご主催の立候補感謝です 🙇 

 ぜひお願いいたします。
さっそくassignをさせていただきました。

開催予定日など決まりましたらこちらでご連絡ください！
また１ヶ月ほど前に募集ページのドラフトを作成させていただきます。

**Comment by tokorom** [comment]
こちらは実施延期となりました。
