### ISSUE TITLE
[延期] 2020年6月のpotatotips （CBcloud様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#71]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- CBcloud株式会社様

### ご担当者様

- @BigBackBoom さん

### 開催日時

-

### 会場

-

**Comment by BigBackBoom** [comment]
@tokorom  初めまして！CBcloud株式会社の @BigBackBoom です。
2020年6月回、ぜひ弊社で開催させてもらえればと思いますがいかがでしょうか。ご確認おねがいいたします！

**Comment by tokorom** [comment]
@BigBackBoom 立候補ありがとうございます。ぜひよろしくお願いいたします！早速、予約を入れさせていただきました。

**Comment by BigBackBoom** [comment]
ありがとうございます！！！！

**Comment by BigBackBoom** [comment]
@tokorom さま。

お疲れ様です。

ご相談なのですが、一身上の都合で私がCBcloudを退職することになりまして、
別の方にイベントの主催を引き継ぎたいのですが、それでも大丈夫でしょうか？

または、一度主催事態をキャンセルしたほうがよろしいでしょうか？

以上です。
よろしくお願いいたします。

菊池

**Comment by tokorom** [comment]
@BigBackBoom おお、そうなのですね！
別のかたに引き継いでいただくのはもちろん歓迎です。
よろしくお願いします。

**Comment by BigBackBoom** [comment]
@tokorom 
ありがとうございます！  

その場合、potatotipsのここのrepositoryに担当の方を追加してもらえばいい感じでしょうか？

ちなみに、mfreeman59という方です。

**Comment by tokorom** [comment]
@BigBackBoom はい！

いま @mfreeman59 さんに招待を送らせていただきました。
お手数ですが @mfreeman59 さんにこのIssueをご紹介お願いします。

**Comment by mfreeman59** [comment]
@tokurom
初めまして！本件引き継ぎましたので、今後のやり取りよろしくお願いいたします。

**Comment by tokorom** [comment]
@mfreeman59 
早速ありがとうございます！こちらのIssueにassignをさせていただきました。

お時間のある時に https://github.com/potatotips/potatotips/blob/master/README.md あたりをご参照ください。

また、開催の２ヶ月前くらいに開催日をご決定いただき、１ヶ月前くらいに募集ページを公開する、という流れになります。
よろしくお願いいたします 🙇

**Comment by tokorom** [comment]
@mfreeman59 6月にpotatotipsのご予約をいただいていたのですが、まだコロナが落ち着いておらず、今の段階でオフラインイベントの募集をかけるのは厳しいかなという印象です。

もしよろしければ２ヶ月ほどシフトいただく or 様子見いただくのはいかがでしょうか。

もし御社でZoomのウェビナーなどオンライン開催の環境をお持ち、かつ、オンラインイベントでも許容いただけるようでしたら、オンライン開催も歓迎です。（その場合、参加者が御社に訪問するというメリットがなくなるなどありますが...

**Comment by mfreeman59** [comment]
@tokorom 
ご返信遅くなってしまい、申し訳ありません。
お伝えいただいた旨、承知いたしました！
一旦様子見としていただいて、状況を見つつ日程を定める方針で問題ないかなと思います。

**Comment by tokorom** [comment]
@mfreeman59 ありがとうございます！では、コロナの状況が落ち着いてきましら改めて相談をさせてください。

また、もし6月にオンラインで実施してくれる会社様が見つかった際には、6月にそれを実施する可能性があることなどご了承願います。
