### ISSUE TITLE
2020年7月のpotatotips （LINE Fukuoka株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#72]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- LINE Fukuoka

https://linefukuoka.co.jp/ja/

### ご担当者様

- @freddi-kit さん

### 開催日時

- 7/10（金）20:00くらいから

### 会場

- オンライン（Zoom Webinar）

**Comment by freddi-kit** [comment]
ありがとうござます！

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @freddi-kit さんを管理者として追加させていただきました。

https://connpass.com/event/178565/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by freddi-kit** [comment]
個人的なDead Line:  6/12

**Comment by freddi-kit** [comment]
もろもろ終えました、明日の13時頃公開しますね

**Comment by tokorom** [comment]
ありがとうございます！よろしくお願いします 🙇

**Comment by freddi-kit** [comment]
広報チェックを入れ忘れたのでちょっと遅れると思います、すいません

**Comment by freddi-kit** [comment]
19頃に公開できるように調整します！

**Comment by freddi-kit** [comment]
広報チェック通ったのでもう公開しますね！

**Comment by tokorom** [comment]
ありがとうございます！！夕方くらいにツイートしまっす。

**Comment by freddi-kit** [comment]
ありがとうございました！改めてこちらから反省点数点上げときます

- connpass のメール機能は即時配信ではないことがある。１時間ほどマージンを見たほうがいい
- zoom webinearのurlは管理者用途参加者用があるので、それらの共有ミスには気をつけること

**Comment by tokorom** [comment]
ご開催およびフィードバックありがとうございました！
いただいた内容もpotatotipsのTipsとして貯めさせていただきます 🙇
