### ISSUE TITLE
2020年10月のpotatotips （アンドパッド様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#75]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- アンドパッド様

### ご担当者様

- @daisuke0131 さん

### 開催日時

-

### 会場

- オンライン開催の予定

**Comment by daisuke0131** [comment]
ありがとうございます！
5/13に社名変更したのでそちらだけ変更させていただきました！
https://lp.andpad.jp/1111/

**Comment by tokorom** [comment]
@daisuke0131 10月のpotatotipsご開催よろしくお願いします！よろしければ開催日程のご調整よろしくお願いします。

**Comment by daisuke0131** [comment]
@tokorom 遅くなってすみません、10月23日（金）とかどうでしょう？

**Comment by tokorom** [comment]
@daisuke0131 ありがとうございます！10月23日（金）よろしくお願いします！
オンラインは過去2回は20:00から開始しているのですが同じく20:00からで大丈夫でしょうか？
懇親会もないため、おおむね21:30くらい、遅くとも22:00までには終わる見込みです。

**Comment by daisuke0131** [comment]
@tokorom 20:00で問題ないです！

**Comment by tokorom** [comment]
募集ページのドラフトを https://connpass.com/event/189012/edit/ に作成させていただきました！
@daisuke0131 さんを管理者として追加しております。

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 が良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by daisuke0131** [comment]
遅くなりましたが、公開しようと思いますー！

**Comment by daisuke0131** [comment]
先ほど公開しました！
https://potatotips.connpass.com/event/189012/

よろしくお願いいたします。

**Comment by tokorom** [comment]
ありがとうございます！！！！

**Comment by tokorom** [comment]
@daisuke0131 今週金曜（10/23）のご開催、よろしくお願いいたします。

さきほどLT発表順をランダムに決定し、こちらに記載し、発表者の皆様に連絡させていただきました。

https://github.com/potatotips/potatotips/wiki/potatotips-71

御社メンバーからのLTご発表などございましたらこちらにWikiに追記をお願いします。
