### ISSUE TITLE
2020年12月のpotatotips （コネヒト株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#77]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- コネヒト株式会社様

### ご担当者様

- あぼさん @YuyaAbo 

### 開催日時

- 12/22

### 会場

- オンライン

**Comment by YuyaAbo** [comment]
@tokorom 度々お世話になっております、コネヒト株式会社のあぼです
12月の回をぜひ弊社で開催させていただきたいのですが、よろしいでしょうか？
オンライン開催になると思います！

**Comment by tokorom** [comment]
@YuyaAbo 

ありがとうございます！ぜひお願いします。
早速

**Comment by tokorom** [comment]
@YuyaAbo 12月のご開催よろしくお願いします！開催日はお任せします。開催日をご教示いただいて募集ページのドラフトを作成させていただきます。

ちなみにですが、例年12月と1月は人が集まりにくい兆候があります。
現在、その先の予約も入れていませんので2月、3月、4月など、もし先の月でのご開催のほうが都合がよろしければご指示ください。

**Comment by YuyaAbo** [comment]
@tokorom 12/22(火) 開催でよろしくお願いします！

> ちなみにですが、例年12月と1月は人が集まりにくい兆候があります。
現在、その先の予約も入れていませんので2月、3月、4月など、もし先の月でのご開催のほうが都合がよろしければご指示ください。

承知しました！オンライン×12月でどうなるかわかりませんが、今回はこのまま12月開催で進めさせてください 👍

**Comment by tokorom** [comment]
うけたまわりました！よろしくお願いいたします。

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @YuyaAbo  さんを管理者として追加させていただきました。

https://connpass.com/event/194575/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待し、それをconnpassからのメールなどで通知いただく想定です
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by YuyaAbo** [comment]
ありがとうございます！

**Comment by YuyaAbo** [comment]
@tokorom イベントページ公開致しました！
https://potatotips.connpass.com/event/194575/

**Comment by tokorom** [comment]
ありがとうございます！！

**Comment by YuyaAbo** [comment]
@tokorom 所さんもウェビナーにパネリストとして参加されますか？（ビデオオンにできるので）
もしくは普通の参加者としてにしますか？

**Comment by tokorom** [comment]
@YuyaAbo 特にビデオオンで発言することはないのですが、念のためパネリストで参加させてください！
当日はオフライン開催と同様にTwitterでのアナウンス（次は〇〇さんでSwiftUIの秘策です #potatotips、的なもの）を担当させていただきます。

**Comment by YuyaAbo** [comment]
承知しました！！！

**Comment by tokorom** [comment]
@YuyaAbo 

当日の発表順をランダムに決定し、 発表者の皆様にconnpassからメッセージを送らせていただきました。

https://connpass.com/event/194575/message/77042/

発表順は、

https://github.com/potatotips/potatotips/wiki/potatotips-72

ですが、運用的に御社メンバーをはじめに固めたいなどございましたらご変更ください！
（通例的にはトップバッターは御社メンバーのほうが良いかと思います

**Comment by YuyaAbo** [comment]
@tokorom ありがとうございます！確認しました！
冒頭で軽い会社紹介をした後にLTに移れればと思うので、トップバッターは僕にしますね。
