### ISSUE TITLE
2021年3月のpotatotips (メドピア株式会社様)

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#79]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- メドピア株式会社

### ご担当者様

- 古田さん @mpg-manami-furuta

### 開催日時

- 3月26日㈮　20時開始(仮）

### 会場

- オンライン開催

**Comment by mpg-manami-furuta** [comment]
@tokorom インバイトありがとうございます。また、開催予定日に所さんの出席が難しいとのこと承知いたしました！
引き続きよろしくお願いいたします。

**Comment by tokorom** [comment]
@mpg-manami-furuta ご開催の立候補ありがとうございます！

当日に、私が参加できる場合はTwitterで #potatotips のハッシュタグで情報を追う方向けに、

```
次は〇〇さんで○○○です (iOS) #potatotips
```

といったLTの発表のアナウンスをしております。
この運用も必須ではないのですが、もしよろしければ御社のどなたかでご担当いただけると嬉しいです。

近日、参加募集ページ（connpass）のドラフトを作成して、こちらでmentionさせていただきます。

**Comment by mpg-manami-furuta** [comment]
@tokorom LTアナウンスも当社にて対応させていただきます。丁寧にご教示いただきありがとうございます。

connpassページのドラフトについてもお待ちしております。よろしくお願いいたします！

**Comment by tokorom** [comment]
@mpg-manami-furuta connpassページを作成中です。 https://connpass.com/event/202810/edit/

@mpg-manami-furuta さんを管理者として招待しますので、こちらでconnpassのアカウント名をご教示ください 🙇

**Comment by mpg-manami-furuta** [comment]
@tokorom ページのご作成ありがとうございます！アカウントはこちらです！https://connpass.com/user/manami61/

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @mpg-manami-furuta   さんを管理者として追加させていただきました。

https://connpass.com/event/202810/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

（以下、Zoom前提で書いていますがZoomでなければいけないわけではありません）

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待し、それをconnpassからのメールなどで通知いただく想定です
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by mpg-manami-furuta** [comment]
@tokorom ご作成いただきありがとうございます。
準備進めて参ります！

**Comment by mpg-manami-furuta** [comment]
@tokorom 準備完了いたしましたので、明日13時公開予定です！

**Comment by tokorom** [comment]
よろしくお願いします！！

**Comment by mpg-manami-furuta** [comment]
@tokorom ページ公開完了しましたm(__)m
https://potatotips.connpass.com/event/202810/

**Comment by tokorom** [comment]
@mpg-manami-furuta 

ありがとうございます！Twitterでも共有させていただきましたー

**Comment by tokorom** [comment]
@mpg-manami-furuta 

3月のご開催ありがとうございました！
私は参加できず残念でした。

またオンライン・オフライン問わずご機会がありましたら是非お願いいたします 🙇‍♂️

**Comment by mpg-manami-furuta** [comment]
@tokorom 
こちらこそ開催を許可していただきありがとうございました！色々とサポートいただき大変助かりました。
参加してみて技術レベルの高さを改めて感じました。当社も引き続きモバイルアプリ開発には力を入れていきたいと考えておりますので、是非また開催させて頂ければと思います！
今後ともよろしくお願いいたします。
