### ISSUE TITLE
2021年6月のpotatotips （ウォンテッドリー株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#80]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- ウォンテッドリー株式会社

### ご担当者様

- 竹内みずきさん @MizuTakeuchi 

### 開催日時

- 6月 23日 (水曜日) 20:00〜 予定

### 会場

- オンライン開催

**Comment by MizuTakeuchi** [comment]
@tokorom 
5月or6月の開催にてぜひご支援できましたら幸いです。
ウォンテッドリー株式会社
竹内みずき
Online
開催日時は追ってご連絡させていただきます。

@kubode

**Comment by tokorom** [comment]
@MizuTakeuchi いつもありがとうございます！！早速、このIssueにassignをさせていただきました。
ぜひよろしくお願いいたします 🙇

**Comment by MizuTakeuchi** [comment]
@tokorom 
こんばんは
一つ相談なのですが、　6/28~30のお日にちですとおそすぎますか？

WWDCの開催後のほうが盛り上がるかなとおもい、事前におうかがいさせて頂きました。

**Comment by tokorom** [comment]
> 6/28~30のお日にちですとおそすぎますか？

まったく問題ありません！

> WWDCの開催後のほうが盛り上がる

賛成です 👍

**Comment by MizuTakeuchi** [comment]
@tokorom 
6月 29日 (火曜日)
上記にてお願い致します。

**Comment by tokorom** [comment]
@MizuTakeuchi 日程のご調整ありがとうございます。6/29（火）に是非よろしくお願いします。また5月になった頃に募集ページのドラフトを作って連絡させていただきます。

**Comment by ShotaKashihara** [comment]
>WWDC21開催のお知らせ
>Apple Worldwide Developers Conferenceが米国太平洋夏時間（PDT）の6月7日〜11日に開催されます。
https://developer.apple.com/jp/news/?id=t5jm3yaz

WWDCの 2週間後なので iOS は新鮮なネタが提供できそうですね！

**Comment by tokorom** [comment]
Glass関連の発表もありそうでホットな会になりそうですね！

**Comment by MizuTakeuchi** [comment]
@tokorom 
すみません、、日程の変更をお願いできますと幸いです。
6月 23日 (水曜日)
何卒よろしくお願いいたします。

**Comment by tokorom** [comment]
@MizuTakeuchi はい！全く

**Comment by tokorom** [comment]
@MizuTakeuchi こちらドラフト作成を失念しておりました。遅くなり失礼しました。本日午前中に作成してTODO整理いたします。

**Comment by tokorom** [comment]
お待たせしました。connpassに募集ページのドラフトを作成し、 @MizuTakeuchi さんを管理者として追加しました。

https://connpass.com/event/214754/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待し、それをconnpassからのメールなどで通知いただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by MizuTakeuchi** [comment]
公開しました🎉
https://potatotips.connpass.com/event/214754/

**Comment by tokorom** [comment]
ありがとうございます！！！！！

**Comment by tokorom** [comment]
@MizuTakeuchi 

明日（6/32）のご開催よろしくお願いします 🙇‍♂️ 

こちらに当日のLT発表順を記載しておりますので、御社メンバーのLTご発表がある場合は追記をお願いします。追記いただく場合、どちらかといえばトップバッターは御社メンバーのほうが望ましいかと思います）。https://github.com/potatotips/potatotips/wiki/potatotips-74

今回、私もLT発表をすることにしたのをご了承願います（先週時点で空きがあったため）。

**Comment by ShotaKashihara** [comment]
>こちらに当日のLT発表順を記載しておりますので、御社メンバーのLTご発表がある場合は追記をお願いします。追記いただく場合、どちらかといえばトップバッターは御社メンバーのほうが望ましいかと思います）。https://github.com/potatotips/potatotips/wiki/potatotips-74

ありがとうございます。弊社からは1人発表をさせていただこうと思います。 @kubode 

>今回、私もLT発表をすることにしたのをご了承願います（先週時点で空きがあったため）。

SharePlay の発表楽しみです！！

**Comment by tokorom** [comment]
@ShotaKashihara ありがとうございます！本日、よろしくお願いいたします 🙇‍♂️

**Comment by ShotaKashihara** [comment]
開催done!

@tokorom 本日は運営および発表ありがとうございました👏
SharePlay入門できていなかったの5分で入門できて最高でした

**Comment by tokorom** [comment]
@ShotaKashihara こちらこそご主催いただき感謝です！素晴らしい司会進行ありがとうございました！
