### ISSUE TITLE
2021年8月のpotatotips （ヘイ株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#81]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- ヘイ株式会社

### ご担当者様

- 坂田さん @huinme

### 開催日時

- 8月前半（予定）

### 会場

- オンライン（予定）

**Comment by huinme** [comment]
@tokorom 

こんにちは！この回の開催を担当させていただければ幸いです。
下記概要です。よろしくお願いします！

- 主催会社 : ヘイ株式会社
- 担当者 : 坂田 @huinme
- 開催日時 : 
	- 1つ前の開催が6月末のようなので、8月前半で検討中です.
- 会場 : オンライン(予定)

**Comment by tokorom** [comment]
@huinme ありがとうございます！ぜひよろしくお願いします。

**Comment by huinme** [comment]
@tokorom 

お世話になってます！
少し早いですが、8月の開催は以下の内容で考えております。

募集開始 : 7月15日 (木)
開催日時 : 8月12日 (木) 20:00 - 21:30
開催場所 : オンライン (ZOOMウェビナーを利用予定)
参加規模 : すべて先着順
	- iOS 発表枠 : 5名
	- Android 発表枠 : 5名
	- オーディエンス枠 : 100名
	
ひとまず上記で問題ないかご確認いただければと思います！

問題なければ7月に入ったタイミングくらいで
ドラフトページの作成をお願いできればと思います。
(こちらからも連絡させてもらいます！)

以上よろしくお願いします！

**Comment by tokorom** [comment]
@huinme ありがとうございます！すべてうけたまわりました。

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、@huinme さんを管理者として追加させていただきました。

https://connpass.com/event/218185/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待いただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by huinme** [comment]
@tokorom 

ページのご用意ありがとうございます！
来週準備しまして、予定どおり7/15 (木)から募集開始できるように進めたいと思います！

**Comment by huinme** [comment]
@tokorom お世話になっております！

connpassですがいったん完成しましたので、もし可能であればチェックいただけるとたすかります！
問題なければ予定通り明日公開いたします
https://potatotips.connpass.com/event/218185/preview/

- - - 

チェックリスト

- [x] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [x] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [x] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [x] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [x] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
	- 後日対応いたします
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待いただく想定です
	- 申込者が規定数あつまりましたら対応予定です. (発表者情報は弊社側でwikiを更新予定です)
- [x] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by tokorom** [comment]
@huinme ありがとうございます！バッチリです 🙇‍♂️

**Comment by huinme** [comment]
@tokorom ご確認ありがとうございます！では明日公開します！

**Comment by huinme** [comment]
公開しました！
https://potatotips.connpass.com/event/218185/

**Comment by huinme** [comment]
@tokorom 昨日はありがとうございました！
もし事後処理必要であれば教えてください！
なければcloseいただければ幸いです！

**Comment by tokorom** [comment]
@huinme 素晴らしいオンライン開催ありがとうございました！またご機会がありましたらぜひお願いします！
