### ISSUE TITLE
2021年10月 or 11月のpotatotips （note株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#82]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- note株式会社

### ご担当者様

- 中西さん @AsakoNakanishi
- 森本さん

### 開催日時

- 11/17（水）20:00

### 会場

- オンライン

**Comment by tokorom** [comment]
@AsakoNakanishi ご開催の日程など決まりましたらまたご教示ください。おおむね開催の1ヶ月前にconnpassに募集ページを公開できればとイメージしております。

**Comment by tokorom** [comment]
@AsakoNakanishi 

ご調整ありがとうございます！
日程その他うけたまわりました！
ドラフトを作成次第、こちらで連絡させていただきます。

**Comment by tokorom** [comment]
@AsakoNakanishi 

参加募集用ドラフトページをconnpassに作成させていただきました！

https://connpass.com/event/224395/edit/

管理者として招待しますので、connpassのアカウントをご教示お願いします 🙇‍♂️

**Comment by AsakoNakanishi** [comment]
@tokorom 
ありがとうございます！！こちらになります！
https://connpass.com/user/AsakoNakanishi/

**Comment by tokorom** [comment]
@AsakoNakanishi 

ありがとうございます！管理者として追加させていただきました。

https://connpass.com/event/224395/edit/

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待いただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by AsakoNakanishi** [comment]
@tokorom 公開しました！

**Comment by tokorom** [comment]
ありがとうございます！！！ 🎉

**Comment by tokorom** [comment]
@AsakoNakanishi 

来週（7/17水）のご開催よろしくお願いします 🙇‍♂️ 

https://github.com/potatotips/potatotips/wiki/potatotips-76

御社メンバーからの追加のLTご発表などある場合はこちらに追記をお願いします。

（先ほど、発表者の皆様にこのページにLTタイトルの記載をお願いするメールを送信させていただきました）

**Comment by AsakoNakanishi** [comment]
@tokorom ありがとうございます！！！ちなみに、ウェビナーのパネリスト用のURLに招待のため、発表者の方のメールアドレスが必要なのですが、tokorom様の方でお持ちでしょうか？もしくは、別でこちらから回収してしまってよいでしょうか？

**Comment by tokorom** [comment]
@AsakoNakanishi 

> ウェビナーのパネリスト用のURLに招待のため、発表者の方のメールアドレスが必要なのですが、tokorom様の方でお持ちでしょうか？

メールアドレス or Zoomアカウントを、connpass上での参加申し込み時にアンケートで発表者の皆様に入力いただいています。

https://connpass.com/event/224395/participants/

から各参加者様の「アンケート回答を表示」で回収お願いします！

**Comment by AsakoNakanishi** [comment]
@tokorom ありがとうございます！！！

**Comment by AsakoNakanishi** [comment]
@tokorom 1名メールアドレスが未入力の方がいらっしゃいますが、こちら、個別回収の方法ってございますでしょうか🙏

**Comment by tokorom** [comment]
@AsakoNakanishi Facebookメッセンジャーで連絡させていただきます。
