### ISSUE TITLE
2022年3月のpotatotips (アンドパッド様)

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#83]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- アンドパッド様

### ご担当者様

- @daisuke0131 さん

### 開催日時

- 2022年3月24日（木）20:00-

### 会場

- オンライン（Zoom）

**Comment by daisuke0131** [comment]
@tokorom 
お疲れ様です。
こちらの枠空いてればANDPADで担当したいのですが可能でしょうか？

**Comment by tokorom** [comment]
@daisuke0131 

もちろん歓迎です！ぜひお願いいたします。
さっそくassignさせていただきました 🙇‍♂️

**Comment by daisuke0131** [comment]
ありがとうございます、よろしくお願いいたします。

**Comment by daisuke0131** [comment]
@tokorom 
自分だけだと連絡忘れそうなので
@ushisantoasobu さんも追加しました。よろしくお願いいたします。

**Comment by daisuke0131** [comment]
@tokorom @ushisantoasobu 
そろそろ開催日を決める感じですかね？

**Comment by tokorom** [comment]
あけましておめでとうございます！
たしかにそろそろですね。
お手数ですが、日程を決めていただき、それにおわせて募集ページのドラフトを作成させてください。

**Comment by daisuke0131** [comment]
社内確認してみたら
3/24とかが良さそうなのでそちらでお願いします。
（結局ちょっと先になってしまってごめんなさい）

**Comment by tokorom** [comment]
@daisuke0131 @ushisantoasobu 

おふたりを管理者として追加してconnpassの募集ページのドラフトを作成させていただきました。

https://connpass.com/event/236238/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待いただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by daisuke0131** [comment]
こちら2月頭くらいに公開開始します。

**Comment by daisuke0131** [comment]
@tokorom 
zoom url等は当日までに置き換えます。
準備できましたので公開します！

**Comment by tokorom** [comment]
ありがとうございます！！

**Comment by tokorom** [comment]
@daisuke0131 
 
potatotipsの3月24日当日ですが、申し訳ありませんが所が参加できない状況です。
お手数おかけしますが、当日のTwitterでの `#potatotips` での進行アナウンスを御社のどなたかにお任せしてもよいでしょうか。
なお、このTwitterの運用自体も必須ではありませんので御社ご判断で実施しなくてもかまいません。

各種ご準備ありがとうございます。
よろしくお願いいたします 🙇‍♂️

**Comment by daisuke0131** [comment]
@tokorom 
進行こういうやつですよね？できると思います！
https://twitter.com/tokorom/status/1460944837813800961

**Comment by tokorom** [comment]
@daisuke0131 

はい！こちらです。
お手数おかけしますがお願いいたします 🙇

**Comment by tokorom** [comment]
さきほど発表予定の皆様にconnpassからメールを送らせていただきました。

https://connpass.com/event/236238/message/100876/

また、

https://github.com/potatotips/potatotips/wiki/potatotips-77

に当日のLT発表順（予定）を記入しておりますので、御社からのLTのご発表などございましたら、こちらに追記をお願いします 🙇‍♂️
