### ISSUE TITLE
2022年6月のpotatotips （ヘイ株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#84]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- ヘイ株式会社

### ご担当者様

- 坂田さん @huinme

### 開催日時

- 6月22日（水） 20:00

### 会場

- オンライン（Zoom）

**Comment by huinme** [comment]
@tokorom 

お世話になってます。
6月末目安に、ヘイ株式会社で開催させていただければと思いますが、可能でしょうか？

**Comment by tokorom** [comment]
@huinme 

もちろん大歓迎です！さっそく名前を入れさせていただきます。

**Comment by huinme** [comment]
@tokorom はい！よろしくお願いします！

**Comment by huinme** [comment]
@tokorom ご無沙汰しております！
今週中に イベントの日取りなど決めてご連絡させていただきます！

**Comment by tokorom** [comment]
@huinme ありがとうございます！
ドラフトの準備など進めさせていただきます 🙇‍♂️

**Comment by huinme** [comment]
@tokorom お疲れ様です！
イベントの日取りですが

募集開始 : 5月23日 (月)
開催 : 6月22日 (水) 20:00 -21:00

にしたいと思うのですが、ご都合いかがでしょうか？
問題なければconnpassのご用意お願いできればと思います！
ちなみに Zoom で開催予定です！

**Comment by tokorom** [comment]
@huinme ご調整ありがとうございます！

> 募集開始 : 5月23日 (月)
> 開催 : 6月22日 (水) 20:00 -21:00

うけたまわりました 👍

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @huinme  さんを管理者として追加させていただきました。

https://connpass.com/event/248347/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by huinme** [comment]
@tokorom ありがとうございます！編集ページ確認できました。
今週メドで対応させていただきます！

**Comment by huinme** [comment]
@tokorom お疲れ様です！ connpassのページ一通り準備できましたので、来週月曜日 (5/23 10:00) をメドに公開＆募集開始しようと思います。

もしそれまでにお気づきの点ありましたら教えていただけると幸いです。よろしくお願いしますー

(以下、確認事項のリストです)

- [x] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [x] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [x] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [x] 募集枠の人数など御社ご状況に合わせてご変更ください
- [x] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [x] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [x] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [x] 参考情報をご一読ください：potatotips開催 Tips [https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips](https://github.com/potatotips/potatotips/wiki/potatotips%E9%96%8B%E5%82%AC-Tips)
