### ISSUE TITLE
2022年10月 （株式会社ゆめみ様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#85]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- 株式会社ゆめみ

### ご担当者様

- @usami-k さん

### 開催日時

- 10月31日（月）20:00

### 会場

- オンライン開催

**Comment by usami-k** [comment]
@tokorom 
もしまだ主催が決まっていなければ、株式会社ゆめみで開催させていただければと思いますが、いかがでしょうか？

**Comment by tokorom** [comment]
@usami-k ありがとうございます！もちろん大歓迎です！！

さっそくassignさせていただきました。

オンラインでのご開催でもオフラインでのご開催でも御社ご都合に合わせてご設定ください 🙇‍♂️

**Comment by usami-k** [comment]
ありがとうございます。よろしくお願いします。

**Comment by hiragram** [comment]
:eyes: オフラインかオンラインか気になっています

**Comment by usami-k** [comment]
オンラインでの開催を予定しています。
なお、日程は調整中ですが、今のところ10月開催を目指しています。

**Comment by usami-k** [comment]
@tokorom 
日程ですが、10月31日（月）20:00開催にしたいと思います。
オンライン開催です。よろしくお願いします。

**Comment by tokorom** [comment]
@usami-k 

うけたまわりました！connpassの募集ページのドラフト準備など進めさせていただきます。

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、 @usami-k さんを管理者として追加させていただきました。

https://connpass.com/event/261215/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オーディエンス向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] LT発表者はZoomのウェビナーにパネリストとして招待いただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません
- [ ] その他、今回の主催は御社であるため、御社ご裁量で各種ご決定をいただいてかまいません

**Comment by usami-k** [comment]
@tokorom 
ありがとうございます。公開準備を進めます。
来週に公開することになるかなと思っていますが、それで大丈夫でしょうか。

**Comment by tokorom** [comment]
@usami-k 

はい！大丈夫です。
よろしくお願いします。

**Comment by usami-k** [comment]
connpass公開しました。

**Comment by tokorom** [comment]
@usami-k 

- さきほど発表順をランダムに決定し、https://github.com/potatotips/potatotips/wiki/potatotips-79 を更新しました
- connpassのページにLT登壇いただける皆様を発表者として追加しました
- 発表者のみなさまにconnpassからメッセージを送らせていただきました https://connpass.com/event/261215/message/

来週当日の運営よろしくおねがいいたします！
