### ISSUE TITLE
2022年12月のpotatotips （株式会社ディー・エヌ・エー様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#86]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

-  株式会社ディー・エヌ・エー

### ご担当者様

- @uhooi さん

### 開催日時

- 2022/12/22(木) 19:00-21:00

### 会場

- 渋谷スクランブルスクエア40F DeNAラウンジ定

### connpass

- https://connpass.com/event/267635/edit/

**Comment by uhooi** [comment]
@tokorom 
株式会社ディー・エヌ・エーで主催させてください！
次は最短で2023年1月でしょうか…？

**Comment by tokorom** [comment]
@uhooi 

ありがとうございます！もちろん大歓迎です。
@uhooi さんをassignをさせていただきました。

> 次は最短で2023年1月でしょうか…？

基本的にはそうなってしまうのですが、１つ前のゆめみさんのご開催が例えば10月などになった場合は、もう少し前倒ししても良いかもしれません。
先になり恐縮ですがよろしくお願いいたします。

**Comment by tokorom** [comment]
はい！もちろんです！

**Comment by tokorom** [comment]
@uhooi 次回、日程調整お願いいたします！12月から3月までいつでも大丈夫です。

**Comment by uhooi** [comment]
承知しました！ 準備を進めるので少々お待ちください。

**Comment by uhooi** [comment]
@tokorom オフラインで開催できるよう調整しているのですが、その場合に potatotips として定めているルールなどはありますか？

**Comment by tokorom** [comment]
@uhooi おお！ひさびさのオフライン嬉しいです。

じつは、コロナ発生以降、初のオフラインで、potatotipsとしての規定は定めておりません。

（丸投げで申し訳ないのですが）御社のイベント規程等にお任せします。

**Comment by uhooi** [comment]
@tokorom もろもろりょうかいです！

オフラインの会場が確保できたので、ハイブリッド開催でお願いしますー！✨（コロナの状況次第ではオンラインのみになるかもですが）

日時: 2022/12/22(木) 19:00-21:00
場所: 渋谷スクランブルスクエア40F DeNAラウンジ

基本的にはLint Night #1と同じような感じでやろうと思っています↓
https://lintnight.connpass.com/event/263931/

**Comment by tokorom** [comment]
@uhooi 

ご調整ありがとうございます！ハイブリッド開催すごい！
connpassのドラフトなど用意します。

**Comment by tokorom** [comment]
@uhooi 

connpassのドラフトページを作成させていただきました！

 https://connpass.com/event/267635/edit/

イベントの説明の部分はLint Nightよりいくつかコピペさせていただきましたが、必要に応じてご自由に修正お願いします。
今回の開催はDeNAさんのイベントという位置付けになるため、potatotipsの名前と体裁だけ維持いただければ、その他、全ての権限が御社にあると考えていただいて大丈夫です。

前日まで固定されない不特定多数の発表者がオフライン・オンラインで混ざると運用が大変かもなと思い、いったん発表者はオフラインに限定してみましたが、その辺りも、もちろんオンライン可に変えていただいてかまいません。

その他、募集ページ公開までのToDoを列挙させていただきます。

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる画像が良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] イベント説明の中でTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 御社からの発表者もご自由に差し込んでいただいてかまいません
- [ ] オーディエンス（オンライン）向けのZoom参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by uhooi** [comment]
事後報告になりますが、イベント公開しました。
何かありましたらご指摘ください🙏
https://potatotips.connpass.com/event/267635/

**Comment by tokorom** [comment]
@uhooi ありがとうございます！
ひさびさのオフライン（ハイブリッド）開催、すごく嬉しいです。感謝です😭

**Comment by tokorom** [comment]
@uhooi 可能でしたら、ぜひオフライン参加させてください！

各種、まるまるやっていただき助かります。

せめて、当日進行ツイートだけでもさせていただきます🙇🏻

**Comment by uhooi** [comment]
@tokorom おお…！ではぜひお越しくださいー！
connpass の申し込みは不要です。
準備はお任せください💪
