### ISSUE TITLE
2023年6月のpotatotips （株式会社AppBrew様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#88]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- [株式会社AppBrew](https://appbrew.io/) 様

### ご担当者様

- @AkkeyLab さん

### 開催日時

- 2023/06/20（火）19:00~22:00（18:45 開場）

### 会場

- オンライン
- 現地: AppBrew本社 東京都文京区本郷1-11-6東接本郷ビル4階

**Comment by AkkeyLab** [comment]
@tokorom 
こちら、[株式会社AppBrew](https://appbrew.io)で主催させてください！
開催形態は感染症の状況も加味したいので、来年以降再度連絡いたします🙇‍♂️

**Comment by tokorom** [comment]
@AkkeyLab 立候補ありがとうございます！初のご開催嬉しいです。ぜひよろしくお願いします！さっそく、 @AkkeyLab さんをassignさせていただきました。

**Comment by tokorom** [comment]
@AkkeyLab potatotipsご開催の件、ありがとうございます。開催月の目安など決まっていましたらご教示ください。

**Comment by AkkeyLab** [comment]
@tokorom 
しばらくご連絡できておらず、申し訳ありません🙇‍♂️
5月頭に連休があること、6月頭頃にWWDCが開催されそうであることを加味して、6月下旬開催で進めたいと考えております。
開催形式などは、4月頭までに決定させ、改めて共有させてください🙏

**Comment by tokorom** [comment]
@AkkeyLab うけたまわりました！よろしくお願いいたします。

**Comment by AkkeyLab** [comment]
@tokorom 
日程など、詳細が決まりましたので、共有させていただきます。
懸念点などありましたら、ご指摘いただけますと幸いです🙇‍♂️

日時：2023/06/20（火）19:00~22:00（18:45 開場）
場所：（株）AppBrew本社 東京都文京区本郷1-11-6東接本郷ビル4階
登壇：オフラインのみで iOS: 6人, Android: 6人
オーディエンス：オフライン 20人, オンライン 100人（YouTube Live を予定しており、実質無制限）
```
18:45~19:15：受付（4階までは入れるので、受付撤収後は随時4階で受付を行う）
19:00~19:10：開催の挨拶
19:10~19:55：前半6*(発表5+前後バッファ2)
19:55~20:05：休憩
20:05~20:50：後半6*(発表5+前後バッファ2)
20:50~21:50：オフライン参加者向け懇親会
21:50~22:00：片付け、完全撤収
```
私の connpass アカウント：
[https://connpass.com/user/AkioItaya](https://connpass.com/user/AkioItaya/)

**Comment by tokorom** [comment]
@AkkeyLab 必要な情報を全てそろえていただきありがとうございます。
またオンフライン・オンラインのハイブリッド開催感謝です！
また5月の初旬に、connpassに募集ページのドラフトなど作成して案内させていただきます。

**Comment by tokorom** [comment]
@AkkeyLab connpassの募集ページのドラフトを以下のとおり作成させていただきました。

https://connpass.com/event/283461/edit/


新型コロナウイルス感染症の感染症法上の位置付け変更がありましたので今回からコロナ（マスク着用のお願いなど）に関する記述を外しています。もし御社ポリシーで必要なことがありましたら追記をお願いします。

その他、募集ページに関するToDoを以下に整理させていただきました。
お手数おかけしますがご確認お願いします :bow:

- [ ] 主催者の社名記載に変更の必要がありましたら修正をお願いします
- [ ] 管理者を必要に応じて追加をお願いします
- [ ] イベント画像の登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください
- [ ] イベントの説明のTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オンライン参加用URLはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません
- [ ] その他、今回の主催は御社であるため、御社ご裁量で各種ご決定をいただいてかまいません

**Comment by AkkeyLab** [comment]
@tokorom 
募集ページの作成ありがとうございます！
編集ページにアクセスできることを確認しましたので、対応進めさせていただきます🙇‍♂️

**Comment by AkkeyLab** [comment]
共有：
募集ページの編集が完了しましたので、2023/05/22 10:00 に公開します！（公開予約）

**Comment by AkkeyLab** [comment]
@tokorom 
お世話になっております、AppBrew の板谷です！

> お疲れ様です。発表タイトルを決めましたので、お伝えできればと思います。githubページへ各自追記してよい状態となりましたら、ご案内をお願いできますでしょうか？お手数おかけいたします。

connpass ページにて上記のコメントを頂いているのですが、私側で Wiki を更新しても問題ないでしょうか…？
お手すきでご確認いただけますと幸いです🙇‍♂️

**Comment by tokorom** [comment]
@AkkeyLab すみません！ちょうど本日WiKi更新予定でしたので、このあとすぐ対応してここでmentionいたします。

**Comment by tokorom** [comment]
@AkkeyLab お待たせしました 🙇‍♂️ 

https://github.com/potatotips/potatotips/wiki/potatotips-82 が編集可能な状態になっております。

### 現在のステータス

- https://connpass.com/event/283461/edit/ の発表者にLT枠の皆様を追加しました
- github/potatotipsに初発表（未招待）のかたを招待しました
- 発表順をランダムに決定し https://github.com/potatotips/potatotips/wiki/potatotips-82 にお名前を記載しました

### このあと

- connpassのイベントメッセージで発表者の皆様にwikiページへの記載のお願いを送ります

**Comment by AkkeyLab** [comment]
爆速で対応していただき、ありがとうございます！！！🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by tokorom** [comment]
@AkkeyLab １点、火曜（と木曜）がどうしても所の都合がつかず、もし可能でしたら、当日、御社のどなたかにTwitterでの「次は誰々さんのLTです...」という進行状況ツイートをお願いできないでしょうか。
Twitterでハッシュタグを追ってくれているかたに、みなさんのツイートがどのLTに対するコメントなのかをざっくりわかるようにするのが目的です。

ハッシュタグ（#potatotips）付きでスクショのような進行状況ツイートをいただけると嬉しいです。

※これは必須ではありません！

![スクリーンショット 2023-02-17 15 27 03](https://user-images.githubusercontent.com/629993/219566657-1ab17d58-352f-45bf-b239-dec585398c32.png)

https://twitter.com/tokorom/status/1605888603275395072

**Comment by tokorom** [comment]
@AkkeyLab 

connpassに

> 発表内容についてですがFlutterに関するものでも可能でしょうか？

という質問がきているのですが、私から「問題なし」の回答をしてしまってもよいでしょうか。

**Comment by AkkeyLab** [comment]
@tokorom 
返信遅くなってしまい、大変申し訳ありません🙇‍♂️

> 当日、御社のどなたかにTwitterでの「次は誰々さんのLTです...」という進行状況ツイートをお願いできないでしょうか。

こちら、承知いたしました！
弊社運営メンバーで対応させていただきます！

> 私から「問題なし」の回答をしてしまってもよいでしょうか。

はい！私も問題ない認識でした！
よろしくお願いします🙇‍♂️

**Comment by tokorom** [comment]
ありがとうございます！
お問い合わせには回答させていただきました。
