### ISSUE TITLE
2023年7月のpotatotips （メドピア株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#89]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- メドピア株式会社様

### ご担当者様

- @ feb19 さん

### 開催日時

- 2023/7/21(金) 19:00〜

### 会場

- 東京都中央区築地1-13-1 銀座松竹スクエア9階

**Comment by feb19** [comment]
よろしくお願いします！日時、会場はこちらで🤲

日時: 2023/7/21(金) 19:00〜
場所: 東京都中央区築地1-13-1 銀座松竹スクエア9階

**Comment by tokorom** [comment]
@feb19 ありがとうございます！ぜひお願いいたます。
オフライン開催なのか、オンライン可のハイブリッド開催なのか、などは全てお任せします。

**Comment by tokorom** [comment]
@feb19 そろそろconnpassの募集ページのドラフトを作ろうと思います。

- オフライン（現地）のみ
- オーディエンスのみオンラインも可
- オーディエンス・発表者どちらもオンライン可

のどのパターンでご開催いただけますか？

**Comment by feb19** [comment]
@tokorom ありがとうございます！
一応発表者はオフライン限定、視聴はオンライン可能という形にさせていただければと思います。

6 月の AppBrew さんの方式を継承させていただく感じでm m
発表者：オフラインのみ iOS: 6人 / Android: 6人
視聴者：オフライン 20人 / オンライン 100 人（YouTube Live）

公開する際は先日行われたイベントのような内容をいくつか編集させていただければと思いますm m
https://zozotech-inc.connpass.com/event/281473/

**Comment by tokorom** [comment]
@feb19 うけたまわりました！
このあとドラフトを作らせていただきます。

> 公開する際は先日行われたイベントのような内容をいくつか編集させていただければと思いますm m

もちろんです！ドラフトはガンガン編集いただいたかまいません。

**Comment by tokorom** [comment]
connpassに募集ページのドラフトを作成し、@feb19  さんを管理者として追加させていただきました。

https://connpass.com/event/287244/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] 主催者の社名記載に変更の必要がありましたら修正をお願いします
- [ ] 管理者を必要に応じて追加をお願いします
- [ ] イベント画像の登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください
- [ ] イベントの説明のTODOマークが付いている箇所、および変更の必要な箇所がありましたらご自由に編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オンライン参加者けのURLなどはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません（募集開始日時なども状況に合わせてご変更ください）
- [ ] その他、今回の主催は御社であるため、御社ご裁量で各種ご決定をいただいてかまいません

**Comment by tokorom** [comment]
@feb19 ご準備・ご配慮ありがとうございます！私も本日は現地参加できないのですが、今晩落ち着いたタイミングもしくは明日朝にTwitterでのアナウンスをさせてください。

**Comment by tokorom** [comment]
@feb19 

来週のpotatotipsご開催よろしくお願いします 🙇 

さきほどconnpassからLT発表者様向けに https://github.com/potatotips/potatotips/wiki/potatotips-83 へのLT内容記載のお願いのメッセージを送らせていただきました。
御社メンバーからのご登壇についても（すでに入力いただいていますが）ご自由に追記ください。

よろしければ当日、私も現地で見学をさせてください。

**Comment by feb19** [comment]
@tokorom ご案内ありがとうございます！先ほど拝見しました！
当日よろしくお願いします！
