### ISSUE TITLE
2024年4月-6月のpotatotips（NOT A HOTEL株式会社様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#93]
ご主催の立候補ありがとうございます。
お手数おかけしますが、ご主催にあたりこちらをご一読お願いいたします。

https://github.com/potatotips/potatotips/blob/master/README.md

### ご主催者様

- NOT A HOTEL株式会社様

### ご担当者様

- HR 冨永 麻美さん @mamiracle2 , 西丸 亮さん

### 開催日時

- 4月26日（金）19:00-

### 会場

- [NOT A HOTEL EXCLUSIVE ASAKUSA](https://notahotel.com/exclusive/asakusa)

**Comment by mamiracle2** [comment]
こんにちは、NOT A HOTELでHRをしている冨永と申します。2022年2月末までクックパッドに在籍しており、恵比寿ガーデンプレイス時代にイベント主催させていただいたことがございます^^

ぜひNOT A HOTELでもイベント主催させていただきたく、立候補いたします！

- 主催者様
   - NOT A HOTEL株式会社 
- ご担当者様
   - HR 冨永 麻美, 西丸 亮
- 開催日時
   - 4月下旬めど
- 会場
   - [NOT A HOTEL EXCLUSIVE ASAKUSA](https://notahotel.com/exclusive/asakusa)

会場がワンフロアだと30名程度、2フロアだと50名程度のためレイアウトや参加人数はこれから企画を詰めたいと考えております。できればオンライン/オフラインのハイブリッド開催としたいですが、こちらも検討の過程で詰めたいと考えております。

飲料と軽食の提供が可能です！どうぞよろしくお願いいたします。

**Comment by tokorom** [comment]
@mamiracle2 4月開催の立候補をいただきありがとうございます！早速assginさせていただきました。
会場や開催形式につきましても開催が近づくまでにご決定いただければ大丈夫です。
ぜひよろしくお願いいたします！

**Comment by tokorom** [comment]
@mamiracle2 potatotipsは4月下旬のご開催の予定でおかわりないでしょうか。おかわりないようでしたら、開催日付をご決定いただき、それにあわせて募集用のconnpassのページのドラフトなど作らせていただこうと思います。
日程的は必要でしたら最大で6月下旬まで伸ばしていただいても問題ありません（例えばGoogleやAppleのカンファレンスが終わった後など）。

**Comment by mamiracle2** [comment]
@tokorom お世話になっております！こちらご連絡が遅くなりすみません。4月26日に開催したいと考えております。
募集ページはtokoromさんにお願いできる形でしょうか？準備が必要な内容をご教示いただけたら、こちらに展開させていただきます^^

よろしくお願いいたします。

**Comment by mamiracle2** [comment]
- 日程：4月26日（金）
- タイムライン：
18:45-19:00	開場（※オンラインは18:55開場）
19:00-19:05	はじめに
19:05-19:40	LT 1（5名）
19:40-19:50	休憩
19:50-20:25	LT 2（5名）
20:25-20:30	ごあいさつLT ＆ おわりに
20:30-21:40	オフライン参加者向け懇親会
21:40-22:00	片付け、完全撤収
- 形式(ハイブリッド)
   - オンライン（定員なし）
   - 会場（定員30程度で調整中）
- 会場
   - NOT A HOTEL EXCLSIVE ASAKUSA
   - https://notahotel.com/exclusive/asakusa
   - 住所非公開のため、参加者には待ち合わせ場所を事前にお送りします

**Comment by tokorom** [comment]
@mamiracle2 ありがとうございます！4月26日にて承りました。近日、所が作成したconpassの募集ページのドラフトを共有いたします。connpassの管理者として招待すべきアカウントをご教示ください。

オンライン参加者の定員ですが、いったん８０名くらいに設定しておき必要に応じて枠を増やす形でいかがでしょうか。

**Comment by mamiracle2** [comment]
> オンライン参加者の定員ですが、いったん８０名くらいに設定しておき必要に応じて枠を増やす形でいかがでしょうか。

はい、良いと思います！

> connpassの管理者として招待すべきアカウントをご教示ください。

一旦私を入れていただきたいのですが、エンジニアメンバーも数名入れたいです。私から追加招待できるようであれば、私のみで構いません。
https://connpass.com/user/mamiracle/

**Comment by mamiracle2** [comment]
こちらコンパスページのOGPとなる画像は社内での手配となりますでしょうか？

**Comment by tokorom** [comment]
> 一旦私を入れていただきたいのですが、エンジニアメンバーも数名入れたいです。

もちろんです。管理者権限で招待しますので、その後、ご自由にメンバー追加いただき、その他内容も編集いただけます。

> こちらコンパスページのOGPとなる画像は社内での手配となりますでしょうか？

はい。本日、募集ページのドラフトを共有しますので、画像その他、編集いただけるようになります。

**Comment by tokorom** [comment]
@mamiracle2 すみません。一部回答できておりませんでした。

> 弊社からもAndroid, iOSで2名ほどLT参加させていただきたいです！
> ごあいさつLTで簡単に会社を紹介したりするのは問題ないでしょうか？
> 飲食に関してはサンドイッチ等個包装の軽食、ポテトチップス（個包装）、ビール・お茶・水を用意しようと思っています

全て問題ありません！4月の回はNOT A HOTEL株式会社様の主催という扱いになりますので、その他、ご自由に調整いただいてかまいません。

**Comment by tokorom** [comment]
@mamiracle2 

connpassに募集ページのドラフトを作成し、 @mamiracle2  さんを管理者として追加させていただきました。

https://connpass.com/event/313875/edit/

以下、このページについてのお願い事項リストになります。
お手数おかけしますがご確認お願いします :bow:

- [ ] 主催者の社名記載に変更の必要がありましたら修正をお願いします
- [ ] 管理者を必要に応じて追加をお願いします
- [ ] イベント画像の登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ] 募集枠の人数など御社ご状況に合わせてご変更ください
- [ ] イベントの説明のTODOマークが付いている箇所、および変更の必要な箇所がありましたらご自由に編集をお願いします
- [ ] LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] オンライン参加者けのURLなどはconnpassの「参加者への情報」に記載をいただく想定です
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません（募集開始日時なども状況に合わせてご変更ください）
- [ ] その他、今回の主催は御社であるため、御社ご裁量で各種ご決定をいただいてかまいません

イベント説明はTODOマークがついている箇所以外も自由に変更いただいてかまいません。特に今回は「入館方法」のセクションの文言が実態とあわないかもしれません。必要に応じて適切な文言に差し替えお願いします！

**Comment by mamiracle2** [comment]
ありがとうございます！確認・対応してご連絡いたしたします。

**Comment by mamiracle2** [comment]
@tokorom こちら入れていただいたのですが、Connpassって事前に参加者にDMできるような機能があるのでしたでしょうか？なければ、Connpassに待ち合わせ場所を書いておいたほうがいいなと思っております。
> 住所非公開のため、参加者の皆様には待ち合わせ場所を事前にお送りします。

合わせて、いつも参加者の方に向けた事前アンケートって設定されてますでしょうか？いつもの開催形式に合わせられればと思っております。

**Comment by tokorom** [comment]
@mamiracle2 

> Connpassって事前に参加者にDMできるような機能があるのでしたでしょうか？なければ、Connpassに待ち合わせ場所を書いておいたほうがいいなと思っております。

DMできる機能はあるのですが、Eメールのため、開封率がいまいち高くなく不確実という印象はあります（メールで届きますと事前に書いておけば概ね見てもらえるとは思うのですが）。
可能でしたら事前にConnpassに待ち合わせ場所を書くほうが確実と思います！

> 合わせて、いつも参加者の方に向けた事前アンケートって設定されてますでしょうか？いつもの開催形式に合わせられればと思っております。

アンケートですが、 https://connpass.com/event/313875/edit/form/ の2点をいつも入れさせていただいています。

1. あなたはiOSアプリもしくはAndroidアプリ開発に関わる活動をしていますか？（connpassアカウントに連携されているGitHubやX/Twitterでその活動が確認できない場合、予告なく参加をキャンセルさせていただく場合があります）
2. 発表者枠のかたはconnpassのアカウントにGitHubアカウントの連携をお願いします。（potatotipsのGitHubリポジトリにアカウントを加えさせていただくためです）

必要でしたら、こちらに項目を追加いただいて大丈夫です。

**Comment by mamiracle2** [comment]
ありがとうございます！Connpassに待ち合わせ場所を書くようにします。アンケートについてもその内容を入れるようにします。

**Comment by tokorom** [comment]
待ち合わせ場所のご記載よろしくお願いします！アンケートの2点はすでに入力してあります。

**Comment by mamiracle2** [comment]
- [ ] 主催者の社名記載に変更の必要がありましたら修正をお願いします
- [ ]  管理者を必要に応じて追加をお願いします
- [ ]  イベント画像の登録（御社が主催であることが視覚的に分かる写真が良いかと思います）
- [ ]  募集枠の人数など御社ご状況に合わせてご変更ください（いったん御社発表者分を差し引いて各4人ずつとしましたが、増やしていただいてかまいません）
- [ ]  イベントの説明のTODOマークが付いている箇所、および変更の必要な箇所がありましたらご自由に編集をお願いします
- [ ]  LTの前後や間に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ]  オンライン参加者けのURLなどはconnpassの「参加者への情報」に記載をいただく想定です（今回は、現地参加者向けの待ち合わせ住所も？）
- [ ]  参考情報をご一読ください：potatotips開催 Tips [https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips](https://github.com/potatotips/potatotips/wiki/potatotips%E9%96%8B%E5%82%AC-Tips)
- [ ]  上記が終わりましたらそのまま公開いただいてかまいません（募集開始日時なども状況に合わせてご変更ください）
- [ ]  その他、今回の主催は御社であるため、御社ご裁量で各種ご決定をいただいてかまいません

**Comment by mamiracle2** [comment]
@tokorom 一通り記載したので、週明けに再度確認して3/26までに公開します！
登壇についてなのですが、ハイブリッドの場合、会場にいる登壇者もZOOMに入室してパネリストとして登壇する形がスムーズかと思っております。過去だと、そのあたりはどのように運営されていますでしょうか？

メモ：パネリストとして参加していただく場合は、登壇者の集合を10分くらい早めようと思う

**Comment by tokorom** [comment]
@mamiracle2 3/26公開うけたまわりました！よろしくお願いします。

> 登壇についてなのですが、ハイブリッドの場合、会場にいる登壇者もZOOMに入室してパネリストとして登壇する形がスムーズかと思っております。過去だと、そのあたりはどのように運営されていますでしょうか？

主催者様ごとに慣れたやりかたでお任せしていますが、過去に多かったのはご提案と一緒で「会場にいる登壇者もZOOMに入室してパネリストとして登壇する形」です。
（その他には、画面とマイクの出力をYouTube Liveで流すというパターンもあったのですが、正直私はその詳しいやり方をわかってはいません...）

> メモ：パネリストとして参加していただく場合は、登壇者の集合を10分くらい早めようと思う

適切かと思います！アンケートに「発表者枠のかたはZoomにパネリストとして招待するメールアドレスを記入してください」という項目を加えておいても良いかもしれません。

**Comment by mamiracle2** [comment]
ありがとうございます！！先ほどページを公開しました。
私たちも今日から拡散していくので、ぜひよろしくお願いします🎊
https://potatotips.connpass.com/event/313875/

----
> 過去に多かったのはご提案と一緒で「会場にいる登壇者もZOOMに入室してパネリストとして登壇する形」です。

こちらで進めます！

> 適切かと思います！アンケートに「発表者枠のかたはZoomにパネリストとして招待するメールアドレスを記入してください」という項目を加えておいても良いかもしれません。

こちらも対応しました。

**Comment by tokorom** [comment]
@mamiracle2 公開ありがとうございます！盛況で発表枠と現地参加枠はすぐにいっぱいになりましたね。

せっかくですのでお時間が許すのであれば発表枠を1名ずつ増枠するなどしてもよいのかもしれません。そのあたりは会場の時間のご都合などに合わせてご調整お任せします！

**Comment by tokorom** [comment]
@mamiracle2 来週4/26（金）のpotatotipsご開催よろしくお願いします！

当日はよろしければ所も現地で見学をさせてください。

開催に先立ち、発表者の発表順をランダムに決定し、

https://github.com/potatotips/potatotips/wiki/potatotips-87

に記載をしました。先頭2名は御社からのご発表枠に設定していますが、必要でしたら追加削除などお願いします。

また、発表者の皆様にこのページにLTタイトルなど記載いただくようお願いのメッセージを送らせていただきました。

https://connpass.com/event/313875/message/134488/

それでは、当日、よろしくお願いいたします 🙇

**Comment by mamiracle2** [comment]
@tokorom ありがとうございます！！

> 当日はよろしければ所も現地で見学をさせてください。

ぜひ所さんも会場にいらしてください。当日はよろしくお願いいたします。

**Comment by mamiracle2** [comment]
@tokorom 懇親会の際って名札など用意される企業さんは多いでしょうか？必要であれば用意したく、ご教示ください。

**Comment by tokorom** [comment]
@mamiracle2 これまでの例だけでいいますと懇親会用に名札をご用意いただくことは少なかったです。記憶にあるのは数回です。

**Comment by mamiracle2** [comment]
承知いたしました！特に用意しません🙇

**Comment by tfandkusu** [comment]
@mamiracle2 初めまして。発表者の高田です。

connpass の「【登壇のご案内】potatotips 87 でLTの発表をいただける皆様へ」メッセージに

> ・事前にパネリストとして招待したいので、メールアドレスをお知らせください

とありましたが、お知らせする先が分からなかったです。
XのDMだと思いましたが、相互フォローでないと送れないです。
お知らせする先を教えて頂けると幸いです。

**Comment by tokorom** [comment]
@tfandkusu さんのメールアドレスはConnpassのアンケートに入力いただいていたのでおそらくそれで問題ないかと思います。
@mamiracle2 ですよね？

**Comment by tfandkusu** [comment]
上記、ウェブピナーの招待 URL が届き、当日使うPCでも開けたので、解決しました。
